var hierarchy =
[
    [ "_NvBufferChromaSubSamplingParams", "struct___nv_buffer_chroma_sub_sampling_params.html", null ],
    [ "_NvBufferCompositeParams", "struct___nv_buffer_composite_params.html", null ],
    [ "_NvBufferCreateParams", "struct___nv_buffer_create_params.html", null ],
    [ "_NvBufferParams", "struct___nv_buffer_params.html", null ],
    [ "_NvBufferParamsEx", "struct___nv_buffer_params_ex.html", null ],
    [ "_NvBufferSyncObjParams", "struct___nv_buffer_sync_obj_params.html", null ],
    [ "_NvBufferSyncObjRec", "struct___nv_buffer_sync_obj_rec.html", null ],
    [ "_NvBufferTransformParams", "struct___nv_buffer_transform_params.html", null ],
    [ "server.action.Action", "classserver_1_1action_1_1_action.html", [
      [ "alert.BrowserAlert", "classalert_1_1_browser_alert.html", null ]
    ] ],
    [ "nlohmann::adl_serializer&lt; ValueType, typename &gt;", "structnlohmann_1_1adl__serializer.html", null ],
    [ "B1", null, [
      [ "nlohmann::detail::conjunction< B1 >", "structnlohmann_1_1detail_1_1conjunction_3_01_b1_01_4.html", null ],
      [ "nlohmann::detail::conjunction< B1 >", "structnlohmann_1_1detail_1_1conjunction_3_01_b1_01_4.html", null ]
    ] ],
    [ "nlohmann::basic_json&lt; ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType &gt;", "classnlohmann_1_1basic__json.html", null ],
    [ "std::binary_function", null, [
      [ "doj::alphanum_less< Ty >", "structdoj_1_1alphanum__less.html", null ],
      [ "doj::alphanum_less< Ty >", "structdoj_1_1alphanum__less.html", null ]
    ] ],
    [ "nlohmann::detail::binary_reader&lt; BasicJsonType, InputAdapterType, SAX &gt;", "classnlohmann_1_1detail_1_1binary__reader.html", null ],
    [ "nlohmann::detail::binary_writer&lt; BasicJsonType, CharType &gt;", "classnlohmann_1_1detail_1_1binary__writer.html", null ],
    [ "BinaryType", null, [
      [ "nlohmann::byte_container_with_subtype< BinaryType >", "classnlohmann_1_1byte__container__with__subtype.html", null ],
      [ "nlohmann::byte_container_with_subtype< BinaryType >", "classnlohmann_1_1byte__container__with__subtype.html", null ]
    ] ],
    [ "nlohmann::detail::dtoa_impl::boundaries", "structnlohmann_1_1detail_1_1dtoa__impl_1_1boundaries.html", null ],
    [ "nlohmann::detail::dtoa_impl::cached_power", "structnlohmann_1_1detail_1_1dtoa__impl_1_1cached__power.html", null ],
    [ "commandLine", "classcommand_line.html", null ],
    [ "nlohmann::detail::container_input_adapter_factory_impl::container_input_adapter_factory&lt; ContainerType, Enable &gt;", "structnlohmann_1_1detail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory.html", null ],
    [ "nlohmann::detail::container_input_adapter_factory_impl::container_input_adapter_factory&lt; ContainerType, void_t&lt; decltype(begin(std::declval&lt; ContainerType &gt;()), end(std::declval&lt; ContainerType &gt;()))&gt; &gt;", "structnlohmann_1_1detail_1_1container__input__adapter__factory__impl_1_1container__input__adaptec6d36799bbab06a12576748f72ebcf00.html", null ],
    [ "csvData", "classcsv_data.html", null ],
    [ "csvReader", "classcsv_reader.html", null ],
    [ "csvWriter", "classcsv_writer.html", null ],
    [ "cudaFont", "classcuda_font.html", null ],
    [ "cudaPointCloud", "classcuda_point_cloud.html", null ],
    [ "cudaVectorTypeInfo&lt; T &gt;", "structcuda_vector_type_info.html", null ],
    [ "cudaVectorTypeInfo&lt; float &gt;", "structcuda_vector_type_info_3_01float_01_4.html", null ],
    [ "cudaVectorTypeInfo&lt; float3 &gt;", "structcuda_vector_type_info_3_01float3_01_4.html", null ],
    [ "cudaVectorTypeInfo&lt; float4 &gt;", "structcuda_vector_type_info_3_01float4_01_4.html", null ],
    [ "cudaVectorTypeInfo&lt; uchar &gt;", "structcuda_vector_type_info_3_01uchar_01_4.html", null ],
    [ "cudaVectorTypeInfo&lt; uchar3 &gt;", "structcuda_vector_type_info_3_01uchar3_01_4.html", null ],
    [ "cudaVectorTypeInfo&lt; uchar4 &gt;", "structcuda_vector_type_info_3_01uchar4_01_4.html", null ],
    [ "db.DatabaseManager", "classdb_1_1_database_manager.html", null ],
    [ "Dataset", null, [
      [ "datasets.mhp.MHPSegmentation", "classdatasets_1_1mhp_1_1_m_h_p_segmentation.html", null ]
    ] ],
    [ "torch.utils.data.Dataset", null, [
      [ "dataset.Dataset", "classdataset_1_1_dataset.html", null ],
      [ "nuswide.NUSWideDataset", "classnuswide_1_1_n_u_s_wide_dataset.html", null ],
      [ "vision.datasets.voc_dataset.VOCDataset", "classvision_1_1datasets_1_1voc__dataset_1_1_v_o_c_dataset.html", null ],
      [ "voc.VOCDataset", "classvoc_1_1_v_o_c_dataset.html", null ]
    ] ],
    [ "depthnet_utils.depthBuffers", "classdepthnet__utils_1_1depth_buffers.html", null ],
    [ "detectNet::Detection", "structdetect_net_1_1_detection.html", null ],
    [ "nlohmann::detail::detector&lt; Default, AlwaysVoid, Op, Args &gt;", "structnlohmann_1_1detail_1_1detector.html", null ],
    [ "nlohmann::detail::detector&lt; Default, void_t&lt; Op&lt; Args... &gt; &gt;, Op, Args... &gt;", "structnlohmann_1_1detail_1_1detector_3_01_default_00_01void__t_3_01_op_3_01_args_8_8_8_01_4_01_4_00_01_op_00_01_args_8_8_8_01_4.html", null ],
    [ "nlohmann::detail::dtoa_impl::diyfp", "structnlohmann_1_1detail_1_1dtoa__impl_1_1diyfp.html", null ],
    [ "tinyxml2::DynArray&lt; T, INITIAL_SIZE &gt;", "classtinyxml2_1_1_dyn_array.html", null ],
    [ "tinyxml2::Entity", "structtinyxml2_1_1_entity.html", null ],
    [ "Event", "class_event.html", null ],
    [ "server.event.Event", "classserver_1_1event_1_1_event.html", null ],
    [ "server.filter.EventFilter", "classserver_1_1filter_1_1_event_filter.html", [
      [ "alert.BrowserAlert", "classalert_1_1_browser_alert.html", null ]
    ] ],
    [ "glDisplay::eventHandler", "structgl_display_1_1event_handler.html", null ],
    [ "glWidget::eventHandler", "structgl_widget_1_1event_handler.html", null ],
    [ "std::exception", null, [
      [ "nlohmann::detail::exception", "classnlohmann_1_1detail_1_1exception.html", [
        [ "nlohmann::detail::invalid_iterator", "classnlohmann_1_1detail_1_1invalid__iterator.html", null ],
        [ "nlohmann::detail::invalid_iterator", "classnlohmann_1_1detail_1_1invalid__iterator.html", null ],
        [ "nlohmann::detail::other_error", "classnlohmann_1_1detail_1_1other__error.html", null ],
        [ "nlohmann::detail::other_error", "classnlohmann_1_1detail_1_1other__error.html", null ],
        [ "nlohmann::detail::out_of_range", "classnlohmann_1_1detail_1_1out__of__range.html", null ],
        [ "nlohmann::detail::out_of_range", "classnlohmann_1_1detail_1_1out__of__range.html", null ],
        [ "nlohmann::detail::parse_error", "classnlohmann_1_1detail_1_1parse__error.html", null ],
        [ "nlohmann::detail::parse_error", "classnlohmann_1_1detail_1_1parse__error.html", null ],
        [ "nlohmann::detail::type_error", "classnlohmann_1_1detail_1_1type__error.html", null ],
        [ "nlohmann::detail::type_error", "classnlohmann_1_1detail_1_1type__error.html", null ]
      ] ],
      [ "nlohmann::detail::exception", "classnlohmann_1_1detail_1_1exception.html", null ]
    ] ],
    [ "nlohmann::detail::utility_internal::Extend&lt; Seq, SeqSize, Rem &gt;", "structnlohmann_1_1detail_1_1utility__internal_1_1_extend.html", null ],
    [ "nlohmann::detail::utility_internal::Extend&lt; integer_sequence&lt; T, Ints... &gt;, SeqSize, 0 &gt;", "structnlohmann_1_1detail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_intse4b696320406a0717efa9a961a507d9c.html", null ],
    [ "nlohmann::detail::utility_internal::Extend&lt; integer_sequence&lt; T, Ints... &gt;, SeqSize, 1 &gt;", "structnlohmann_1_1detail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_ints55b30810c0f772136f5c0a2221b86a09.html", null ],
    [ "nlohmann::detail::external_constructor&lt; value_t &gt;", "structnlohmann_1_1detail_1_1external__constructor.html", null ],
    [ "nlohmann::detail::external_constructor&lt; value_t::array &gt;", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1array_01_4.html", null ],
    [ "nlohmann::detail::external_constructor&lt; value_t::binary &gt;", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1binary_01_4.html", null ],
    [ "nlohmann::detail::external_constructor&lt; value_t::boolean &gt;", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1boolean_01_4.html", null ],
    [ "nlohmann::detail::external_constructor&lt; value_t::number_float &gt;", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__float_01_4.html", null ],
    [ "nlohmann::detail::external_constructor&lt; value_t::number_integer &gt;", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__integer_01_4.html", null ],
    [ "nlohmann::detail::external_constructor&lt; value_t::number_unsigned &gt;", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4.html", null ],
    [ "nlohmann::detail::external_constructor&lt; value_t::object &gt;", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1object_01_4.html", null ],
    [ "nlohmann::detail::external_constructor&lt; value_t::string &gt;", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1string_01_4.html", null ],
    [ "std::false_type", null, [
      [ "nlohmann::detail::has_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__from__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01f77b5e367f2d5612b4276a155bf11896.html", null ],
      [ "nlohmann::detail::has_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__from__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01f77b5e367f2d5612b4276a155bf11896.html", null ],
      [ "nlohmann::detail::has_non_default_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__non__default__from__json_3_01_basic_json_type_00_01_t_00_01enab072547deb606b69b2d65cb910e223bb8.html", null ],
      [ "nlohmann::detail::has_non_default_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__non__default__from__json_3_01_basic_json_type_00_01_t_00_01enab072547deb606b69b2d65cb910e223bb8.html", null ],
      [ "nlohmann::detail::has_to_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__to__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01_96b7bbbe462cd4ff87697dab3bc993a77.html", null ],
      [ "nlohmann::detail::has_to_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__to__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01_96b7bbbe462cd4ff87697dab3bc993a77.html", null ],
      [ "nlohmann::detail::is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "structnlohmann_1_1detail_1_1is__basic__json_3_01_n_l_o_h_m_a_n_n___b_a_s_i_c___j_s_o_n___t_p_l_01_4.html", null ],
      [ "nlohmann::detail::is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "structnlohmann_1_1detail_1_1is__basic__json_3_01_n_l_o_h_m_a_n_n___b_a_s_i_c___j_s_o_n___t_p_l_01_4.html", null ],
      [ "nlohmann::detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, enable_if_t< is_detected< value_type_t, CompatibleArrayType >::value &&is_detected< iterator_t, CompatibleArrayType >::value &&!is_iterator_traits< iterator_traits< CompatibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl_3_01_basic_json_type_00_01_compati48bb30a3298fd067e7b3dce036e40849.html", null ],
      [ "nlohmann::detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, enable_if_t< is_detected< value_type_t, CompatibleArrayType >::value &&is_detected< iterator_t, CompatibleArrayType >::value &&!is_iterator_traits< iterator_traits< CompatibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl_3_01_basic_json_type_00_01_compati48bb30a3298fd067e7b3dce036e40849.html", null ],
      [ "nlohmann::detail::is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, enable_if_t< std::is_integral< RealIntegerType >::value &&std::is_integral< CompatibleNumberIntegerType >::value &&!std::is_same< bool, CompatibleNumberIntegerType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01_real_integer_type_00_01_combbf637f45e4984de1d118b9d7a65e604.html", null ],
      [ "nlohmann::detail::is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, enable_if_t< std::is_integral< RealIntegerType >::value &&std::is_integral< CompatibleNumberIntegerType >::value &&!std::is_same< bool, CompatibleNumberIntegerType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01_real_integer_type_00_01_combbf637f45e4984de1d118b9d7a65e604.html", null ],
      [ "nlohmann::detail::is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, enable_if_t< is_detected< mapped_type_t, CompatibleObjectType >::value &&is_detected< key_type_t, CompatibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01_basic_json_type_00_01_compat5b5eeaa8fc54c99a69d765462ac539f5.html", null ],
      [ "nlohmann::detail::is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, enable_if_t< is_detected< mapped_type_t, CompatibleObjectType >::value &&is_detected< key_type_t, CompatibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01_basic_json_type_00_01_compat5b5eeaa8fc54c99a69d765462ac539f5.html", null ],
      [ "nlohmann::detail::is_compatible_string_type_impl< BasicJsonType, ConstructibleStringType >", "structnlohmann_1_1detail_1_1is__compatible__string__type__impl.html", [
        [ "nlohmann::detail::is_compatible_string_type< BasicJsonType, ConstructibleStringType >", "structnlohmann_1_1detail_1_1is__compatible__string__type.html", null ],
        [ "nlohmann::detail::is_compatible_string_type< BasicJsonType, ConstructibleStringType >", "structnlohmann_1_1detail_1_1is__compatible__string__type.html", null ]
      ] ],
      [ "nlohmann::detail::is_compatible_string_type_impl< BasicJsonType, CompatibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, CompatibleStringType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__string__type__impl_3_01_basic_json_type_00_01_compat6590904cab40fc73f430e4c7518179a2.html", null ],
      [ "nlohmann::detail::is_compatible_string_type_impl< BasicJsonType, ConstructibleStringType >", "structnlohmann_1_1detail_1_1is__compatible__string__type__impl.html", null ],
      [ "nlohmann::detail::is_compatible_string_type_impl< BasicJsonType, CompatibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, CompatibleStringType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__string__type__impl_3_01_basic_json_type_00_01_compat6590904cab40fc73f430e4c7518179a2.html", null ],
      [ "nlohmann::detail::is_compatible_type_impl< BasicJsonType, CompatibleType, enable_if_t< is_complete_type< CompatibleType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__type__impl_3_01_basic_json_type_00_01_compatible_typ632bee7ec037fc0233f1bbe9dd7d8874.html", null ],
      [ "nlohmann::detail::is_compatible_type_impl< BasicJsonType, CompatibleType, enable_if_t< is_complete_type< CompatibleType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__type__impl_3_01_basic_json_type_00_01_compatible_typ632bee7ec037fc0233f1bbe9dd7d8874.html", null ],
      [ "nlohmann::detail::is_complete_type< T, decltype(void(sizeof(T)))>", "structnlohmann_1_1detail_1_1is__complete__type_3_01_t_00_01decltype_07void_07sizeof_07_t_08_08_08_4.html", null ],
      [ "nlohmann::detail::is_complete_type< T, decltype(void(sizeof(T)))>", "structnlohmann_1_1detail_1_1is__complete__type_3_01_t_00_01decltype_07void_07sizeof_07_t_08_08_08_4.html", null ],
      [ "nlohmann::detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< !std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value &&is_default_constructible< ConstructibleArrayType >::value &&(std::is_move_assignable< ConstructibleArrayType >::value||std::is_copy_assignable< ConstructibleArrayType >::value)&&is_detected< value_type_t, ConstructibleArrayType >::value &&is_detected< iterator_t, ConstructibleArrayType >::value &&is_complete_type< detected_t< value_type_t, ConstructibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_cons68b4bfb1ff156af9105b063db2209d6d.html", null ],
      [ "nlohmann::detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_cons8cf88e17d5eaa68665a8fb4b97604b0e.html", null ],
      [ "nlohmann::detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< !std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value &&is_default_constructible< ConstructibleArrayType >::value &&(std::is_move_assignable< ConstructibleArrayType >::value||std::is_copy_assignable< ConstructibleArrayType >::value)&&is_detected< value_type_t, ConstructibleArrayType >::value &&is_detected< iterator_t, ConstructibleArrayType >::value &&is_complete_type< detected_t< value_type_t, ConstructibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_cons68b4bfb1ff156af9105b063db2209d6d.html", null ],
      [ "nlohmann::detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_cons8cf88e17d5eaa68665a8fb4b97604b0e.html", null ],
      [ "nlohmann::detail::is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, enable_if_t< is_detected< mapped_type_t, ConstructibleObjectType >::value &&is_detected< key_type_t, ConstructibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl_3_01_basic_json_type_00_01_con1038de539babd212ea0aef1cc5752545.html", null ],
      [ "nlohmann::detail::is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, enable_if_t< is_detected< mapped_type_t, ConstructibleObjectType >::value &&is_detected< key_type_t, ConstructibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl_3_01_basic_json_type_00_01_con1038de539babd212ea0aef1cc5752545.html", null ],
      [ "nlohmann::detail::is_constructible_string_type_impl< BasicJsonType, ConstructibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, ConstructibleStringType >::value > >", "structnlohmann_1_1detail_1_1is__constructible__string__type__impl_3_01_basic_json_type_00_01_con83e8ebfe9593f851a60fdb8360df1512.html", null ],
      [ "nlohmann::detail::is_constructible_string_type_impl< BasicJsonType, ConstructibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, ConstructibleStringType >::value > >", "structnlohmann_1_1detail_1_1is__constructible__string__type__impl_3_01_basic_json_type_00_01_con83e8ebfe9593f851a60fdb8360df1512.html", null ],
      [ "nlohmann::detail::is_constructible_tuple< T1, std::tuple< Args... > >", "structnlohmann_1_1detail_1_1is__constructible__tuple_3_01_t1_00_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_constructible_tuple< T1, std::tuple< Args... > >", "structnlohmann_1_1detail_1_1is__constructible__tuple_3_01_t1_00_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_iterator_traits< iterator_traits< T > >", "structnlohmann_1_1detail_1_1is__iterator__traits_3_01iterator__traits_3_01_t_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_iterator_traits< iterator_traits< T > >", "structnlohmann_1_1detail_1_1is__iterator__traits_3_01iterator__traits_3_01_t_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_json_ref< json_ref< T > >", "structnlohmann_1_1detail_1_1is__json__ref_3_01json__ref_3_01_t_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_json_ref< json_ref< T > >", "structnlohmann_1_1detail_1_1is__json__ref_3_01json__ref_3_01_t_01_4_01_4.html", null ],
      [ "__image_format_assert_false< T >", "struct____image__format__assert__false.html", null ],
      [ "__image_format_assert_false< T >", "struct____image__format__assert__false.html", null ],
      [ "cuda_assert_false< T >", "structcuda__assert__false.html", null ],
      [ "cuda_assert_false< T >", "structcuda__assert__false.html", null ],
      [ "nlohmann::detail::has_from_json< BasicJsonType, T, typename >", "structnlohmann_1_1detail_1_1has__from__json.html", null ],
      [ "nlohmann::detail::has_from_json< BasicJsonType, T, typename >", "structnlohmann_1_1detail_1_1has__from__json.html", null ],
      [ "nlohmann::detail::has_non_default_from_json< BasicJsonType, T, typename >", "structnlohmann_1_1detail_1_1has__non__default__from__json.html", null ],
      [ "nlohmann::detail::has_non_default_from_json< BasicJsonType, T, typename >", "structnlohmann_1_1detail_1_1has__non__default__from__json.html", null ],
      [ "nlohmann::detail::has_to_json< BasicJsonType, T, typename >", "structnlohmann_1_1detail_1_1has__to__json.html", null ],
      [ "nlohmann::detail::has_to_json< BasicJsonType, T, typename >", "structnlohmann_1_1detail_1_1has__to__json.html", null ],
      [ "nlohmann::detail::is_basic_json< typename >", "structnlohmann_1_1detail_1_1is__basic__json.html", null ],
      [ "nlohmann::detail::is_basic_json< typename >", "structnlohmann_1_1detail_1_1is__basic__json.html", null ],
      [ "nlohmann::detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, typename >", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl.html", [
        [ "nlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >", "structnlohmann_1_1detail_1_1is__compatible__array__type.html", null ],
        [ "nlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >", "structnlohmann_1_1detail_1_1is__compatible__array__type.html", null ]
      ] ],
      [ "nlohmann::detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, typename >", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl.html", null ],
      [ "nlohmann::detail::is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, typename >", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl.html", [
        [ "nlohmann::detail::is_compatible_integer_type< RealIntegerType, CompatibleNumberIntegerType >", "structnlohmann_1_1detail_1_1is__compatible__integer__type.html", null ],
        [ "nlohmann::detail::is_compatible_integer_type< RealIntegerType, CompatibleNumberIntegerType >", "structnlohmann_1_1detail_1_1is__compatible__integer__type.html", null ]
      ] ],
      [ "nlohmann::detail::is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, typename >", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl.html", null ],
      [ "nlohmann::detail::is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, typename >", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl.html", [
        [ "nlohmann::detail::is_compatible_object_type< BasicJsonType, CompatibleObjectType >", "structnlohmann_1_1detail_1_1is__compatible__object__type.html", null ],
        [ "nlohmann::detail::is_compatible_object_type< BasicJsonType, CompatibleObjectType >", "structnlohmann_1_1detail_1_1is__compatible__object__type.html", null ]
      ] ],
      [ "nlohmann::detail::is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, typename >", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl.html", null ],
      [ "nlohmann::detail::is_compatible_string_type_impl< BasicJsonType, CompatibleStringType, typename >", "structnlohmann_1_1detail_1_1is__compatible__string__type__impl.html", null ],
      [ "nlohmann::detail::is_compatible_string_type_impl< BasicJsonType, CompatibleStringType, typename >", "structnlohmann_1_1detail_1_1is__compatible__string__type__impl.html", null ],
      [ "nlohmann::detail::is_compatible_type_impl< BasicJsonType, CompatibleType, typename >", "structnlohmann_1_1detail_1_1is__compatible__type__impl.html", [
        [ "nlohmann::detail::is_compatible_type< BasicJsonType, CompatibleType >", "structnlohmann_1_1detail_1_1is__compatible__type.html", null ],
        [ "nlohmann::detail::is_compatible_type< BasicJsonType, CompatibleType >", "structnlohmann_1_1detail_1_1is__compatible__type.html", null ]
      ] ],
      [ "nlohmann::detail::is_compatible_type_impl< BasicJsonType, CompatibleType, typename >", "structnlohmann_1_1detail_1_1is__compatible__type__impl.html", null ],
      [ "nlohmann::detail::is_complete_type< T, typename >", "structnlohmann_1_1detail_1_1is__complete__type.html", null ],
      [ "nlohmann::detail::is_complete_type< T, typename >", "structnlohmann_1_1detail_1_1is__complete__type.html", null ],
      [ "nlohmann::detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, typename >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl.html", [
        [ "nlohmann::detail::is_constructible_array_type< BasicJsonType, ConstructibleArrayType >", "structnlohmann_1_1detail_1_1is__constructible__array__type.html", null ],
        [ "nlohmann::detail::is_constructible_array_type< BasicJsonType, ConstructibleArrayType >", "structnlohmann_1_1detail_1_1is__constructible__array__type.html", null ]
      ] ],
      [ "nlohmann::detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, typename >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl.html", null ],
      [ "nlohmann::detail::is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, typename >", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl.html", [
        [ "nlohmann::detail::is_constructible_object_type< BasicJsonType, ConstructibleObjectType >", "structnlohmann_1_1detail_1_1is__constructible__object__type.html", null ],
        [ "nlohmann::detail::is_constructible_object_type< BasicJsonType, ConstructibleObjectType >", "structnlohmann_1_1detail_1_1is__constructible__object__type.html", null ]
      ] ],
      [ "nlohmann::detail::is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, typename >", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl.html", null ],
      [ "nlohmann::detail::is_constructible_string_type_impl< BasicJsonType, ConstructibleStringType, typename >", "structnlohmann_1_1detail_1_1is__constructible__string__type__impl.html", [
        [ "nlohmann::detail::is_constructible_string_type< BasicJsonType, ConstructibleStringType >", "structnlohmann_1_1detail_1_1is__constructible__string__type.html", null ],
        [ "nlohmann::detail::is_constructible_string_type< BasicJsonType, ConstructibleStringType >", "structnlohmann_1_1detail_1_1is__constructible__string__type.html", null ]
      ] ],
      [ "nlohmann::detail::is_constructible_string_type_impl< BasicJsonType, ConstructibleStringType, typename >", "structnlohmann_1_1detail_1_1is__constructible__string__type__impl.html", null ],
      [ "nlohmann::detail::is_constructible_tuple< T1, T2 >", "structnlohmann_1_1detail_1_1is__constructible__tuple.html", null ],
      [ "nlohmann::detail::is_constructible_tuple< T1, T2 >", "structnlohmann_1_1detail_1_1is__constructible__tuple.html", null ],
      [ "nlohmann::detail::is_iterator_traits< T, typename >", "structnlohmann_1_1detail_1_1is__iterator__traits.html", null ],
      [ "nlohmann::detail::is_iterator_traits< T, typename >", "structnlohmann_1_1detail_1_1is__iterator__traits.html", null ],
      [ "nlohmann::detail::is_json_ref< typename >", "structnlohmann_1_1detail_1_1is__json__ref.html", null ],
      [ "nlohmann::detail::is_json_ref< typename >", "structnlohmann_1_1detail_1_1is__json__ref.html", null ]
    ] ],
    [ "nlohmann::detail::file_input_adapter", "classnlohmann_1_1detail_1_1file__input__adapter.html", null ],
    [ "nlohmann::detail::from_json_fn", "structnlohmann_1_1detail_1_1from__json__fn.html", null ],
    [ "nlohmann::detail::utility_internal::Gen&lt; T, N &gt;", "structnlohmann_1_1detail_1_1utility__internal_1_1_gen.html", null ],
    [ "nlohmann::detail::utility_internal::Gen&lt; T, 0 &gt;", "structnlohmann_1_1detail_1_1utility__internal_1_1_gen_3_01_t_00_010_01_4.html", null ],
    [ "glBuffer", "classgl_buffer.html", null ],
    [ "glCamera", "classgl_camera.html", null ],
    [ "glTexture", "classgl_texture.html", null ],
    [ "glWidget", "classgl_widget.html", null ],
    [ "cudaFont::GlyphInfo", "structcuda_font_1_1_glyph_info.html", null ],
    [ "gstBufferManager", "classgst_buffer_manager.html", null ],
    [ "gstWebRTC", "classgst_web_r_t_c.html", null ],
    [ "std::hash&lt; nlohmann::json &gt;", "structstd_1_1hash_3_01nlohmann_1_1json_01_4.html", null ],
    [ "WebRTCServer::HttpRoute", "struct_web_r_t_c_server_1_1_http_route.html", null ],
    [ "nlohmann::detail::identity_tag&lt; T &gt;", "structnlohmann_1_1detail_1_1identity__tag.html", null ],
    [ "nvinfer1::ILogger", null, [
      [ "tensorNet::Logger", "classtensor_net_1_1_logger.html", null ]
    ] ],
    [ "imageFormatType&lt; format &gt;", "structimage_format_type.html", null ],
    [ "imageFormatType&lt; IMAGE_RGB32F &gt;", "structimage_format_type_3_01_i_m_a_g_e___r_g_b32_f_01_4.html", null ],
    [ "imageFormatType&lt; IMAGE_RGB8 &gt;", "structimage_format_type_3_01_i_m_a_g_e___r_g_b8_01_4.html", null ],
    [ "imageFormatType&lt; IMAGE_RGBA32F &gt;", "structimage_format_type_3_01_i_m_a_g_e___r_g_b_a32_f_01_4.html", null ],
    [ "imageFormatType&lt; IMAGE_RGBA8 &gt;", "structimage_format_type_3_01_i_m_a_g_e___r_g_b_a8_01_4.html", null ],
    [ "nlohmann::detail::input_stream_adapter", "classnlohmann_1_1detail_1_1input__stream__adapter.html", null ],
    [ "InputDevices", "class_input_devices.html", null ],
    [ "nlohmann::detail::integer_sequence&lt; T, Ints &gt;", "structnlohmann_1_1detail_1_1integer__sequence.html", null ],
    [ "std::integral_constant", null, [
      [ "std::tuple_size<::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__size_3_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01_iterator_type_01_4_01_4.html", null ],
      [ "std::tuple_size<::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__size_3_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01_iterator_type_01_4_01_4.html", null ]
    ] ],
    [ "nlohmann::detail::internal_iterator&lt; BasicJsonType &gt;", "structnlohmann_1_1detail_1_1internal__iterator.html", null ],
    [ "nvinfer1::IProfiler", null, [
      [ "tensorNet::Profiler", "classtensor_net_1_1_profiler.html", null ]
    ] ],
    [ "NetworkInterface::IPv4", "struct_network_interface_1_1_i_pv4.html", null ],
    [ "NetworkInterface::IPv6", "struct_network_interface_1_1_i_pv6.html", null ],
    [ "std::is_constructible", null, [
      [ "nlohmann::detail::is_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_constructible< T, Args >", "structnlohmann_1_1detail_1_1is__constructible.html", null ],
      [ "nlohmann::detail::is_constructible< T, Args >", "structnlohmann_1_1detail_1_1is__constructible.html", null ]
    ] ],
    [ "std::is_default_constructible", null, [
      [ "nlohmann::detail::is_default_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", [
        [ "nlohmann::detail::is_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "nlohmann::detail::is_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ]
      ] ],
      [ "nlohmann::detail::is_default_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", [
        [ "nlohmann::detail::is_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "nlohmann::detail::is_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ]
      ] ],
      [ "nlohmann::detail::is_default_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", [
        [ "nlohmann::detail::is_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "nlohmann::detail::is_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ]
      ] ],
      [ "nlohmann::detail::is_default_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", [
        [ "nlohmann::detail::is_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "nlohmann::detail::is_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ]
      ] ],
      [ "nlohmann::detail::is_default_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_default_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_default_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_default_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_default_constructible< T >", "structnlohmann_1_1detail_1_1is__default__constructible.html", null ],
      [ "nlohmann::detail::is_default_constructible< T >", "structnlohmann_1_1detail_1_1is__default__constructible.html", null ]
    ] ],
    [ "nlohmann::detail::is_getable&lt; BasicJsonType, T &gt;", "structnlohmann_1_1detail_1_1is__getable.html", null ],
    [ "nlohmann::detail::is_iterator_of_multibyte&lt; T &gt;", "structnlohmann_1_1detail_1_1is__iterator__of__multibyte.html", null ],
    [ "nlohmann::detail::is_sax&lt; SAX, BasicJsonType &gt;", "structnlohmann_1_1detail_1_1is__sax.html", null ],
    [ "nlohmann::detail::is_sax_static_asserts&lt; SAX, BasicJsonType &gt;", "structnlohmann_1_1detail_1_1is__sax__static__asserts.html", null ],
    [ "nlohmann::detail::iter_impl&lt; BasicJsonType &gt;", "classnlohmann_1_1detail_1_1iter__impl.html", null ],
    [ "nlohmann::detail::iteration_proxy&lt; IteratorType &gt;", "classnlohmann_1_1detail_1_1iteration__proxy.html", null ],
    [ "nlohmann::detail::iteration_proxy_value&lt; IteratorType &gt;", "classnlohmann_1_1detail_1_1iteration__proxy__value.html", null ],
    [ "nlohmann::detail::iterator_input_adapter&lt; IteratorType &gt;", "classnlohmann_1_1detail_1_1iterator__input__adapter.html", null ],
    [ "nlohmann::detail::iterator_input_adapter_factory&lt; IteratorType, Enable &gt;", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory.html", null ],
    [ "nlohmann::detail::iterator_input_adapter_factory&lt; IteratorType, enable_if_t&lt; is_iterator_of_multibyte&lt; IteratorType &gt;::value &gt; &gt;", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory_3_01_iterator_type_00_01enable__ifdbe9caa11c2ca51101ba1bbd1184c22c.html", null ],
    [ "nlohmann::detail::iterator_traits&lt; T, typename &gt;", "structnlohmann_1_1detail_1_1iterator__traits.html", null ],
    [ "nlohmann::detail::iterator_traits&lt; T *, enable_if_t&lt; std::is_object&lt; T &gt;::value &gt; &gt;", "structnlohmann_1_1detail_1_1iterator__traits_3_01_t_01_5_00_01enable__if__t_3_01std_1_1is__objec8d960665487688165530972cda4f1bea.html", null ],
    [ "nlohmann::detail::iterator_types&lt; It, typename &gt;", "structnlohmann_1_1detail_1_1iterator__types.html", null ],
    [ "nlohmann::detail::iterator_types&lt; It, void_t&lt; typename It::difference_type, typename It::value_type, typename It::pointer, typename It::reference, typename It::iterator_category &gt; &gt;", "structnlohmann_1_1detail_1_1iterator__types_3_01_it_00_01void__t_3_01typename_01_it_1_1differenc4a413e9bd546446175f10f15c5631361.html", null ],
    [ "nlohmann::detail::iterator_types&lt; T &gt;", "structnlohmann_1_1detail_1_1iterator__types.html", [
      [ "nlohmann::detail::iterator_traits< T, enable_if_t< !std::is_pointer< T >::value > >", "structnlohmann_1_1detail_1_1iterator__traits_3_01_t_00_01enable__if__t_3_01_9std_1_1is__pointer_3_01_t_01_4_1_1value_01_4_01_4.html", null ],
      [ "nlohmann::detail::iterator_traits< T, enable_if_t< !std::is_pointer< T >::value > >", "structnlohmann_1_1detail_1_1iterator__traits_3_01_t_00_01enable__if__t_3_01_9std_1_1is__pointer_3_01_t_01_4_1_1value_01_4_01_4.html", null ]
    ] ],
    [ "JoystickDevice", "class_joystick_device.html", null ],
    [ "nlohmann::json_pointer&lt; BasicJsonType &gt;", "classnlohmann_1_1json__pointer.html", null ],
    [ "nlohmann::detail::json_ref&lt; BasicJsonType &gt;", "classnlohmann_1_1detail_1_1json__ref.html", null ],
    [ "nlohmann::json_sax&lt; BasicJsonType &gt;", "structnlohmann_1_1json__sax.html", null ],
    [ "nlohmann::detail::json_sax_acceptor&lt; BasicJsonType &gt;", "classnlohmann_1_1detail_1_1json__sax__acceptor.html", null ],
    [ "nlohmann::detail::json_sax_dom_callback_parser&lt; BasicJsonType &gt;", "classnlohmann_1_1detail_1_1json__sax__dom__callback__parser.html", null ],
    [ "nlohmann::detail::json_sax_dom_parser&lt; BasicJsonType &gt;", "classnlohmann_1_1detail_1_1json__sax__dom__parser.html", null ],
    [ "KeyboardDevice", "class_keyboard_device.html", null ],
    [ "poseNet::ObjectPose::Keypoint", "structpose_net_1_1_object_pose_1_1_keypoint.html", null ],
    [ "tensorNet::layerInfo", "structtensor_net_1_1layer_info.html", null ],
    [ "nlohmann::detail::lexer_base&lt; BasicJsonType &gt;", "classnlohmann_1_1detail_1_1lexer__base.html", [
      [ "nlohmann::detail::lexer< BasicJsonType, InputAdapterType >", "classnlohmann_1_1detail_1_1lexer.html", null ],
      [ "nlohmann::detail::lexer< BasicJsonType, InputAdapterType >", "classnlohmann_1_1detail_1_1lexer.html", null ]
    ] ],
    [ "Log", "class_log.html", null ],
    [ "tinyxml2::LongFitsIntoSizeTMinusOne&lt; bool &gt;", "structtinyxml2_1_1_long_fits_into_size_t_minus_one.html", null ],
    [ "tinyxml2::LongFitsIntoSizeTMinusOne&lt; false &gt;", "structtinyxml2_1_1_long_fits_into_size_t_minus_one_3_01false_01_4.html", null ],
    [ "nlohmann::detail::make_void&lt; Ts &gt;", "structnlohmann_1_1detail_1_1make__void.html", null ],
    [ "eval_ssd.MeanAPEvaluator", "classeval__ssd_1_1_mean_a_p_evaluator.html", null ],
    [ "tinyxml2::MemPool", "classtinyxml2_1_1_mem_pool.html", [
      [ "tinyxml2::MemPoolT< sizeof(tinyxml2::XMLElement) >", "classtinyxml2_1_1_mem_pool_t.html", null ],
      [ "tinyxml2::MemPoolT< sizeof(tinyxml2::XMLAttribute) >", "classtinyxml2_1_1_mem_pool_t.html", null ],
      [ "tinyxml2::MemPoolT< sizeof(tinyxml2::XMLText) >", "classtinyxml2_1_1_mem_pool_t.html", null ],
      [ "tinyxml2::MemPoolT< sizeof(tinyxml2::XMLComment) >", "classtinyxml2_1_1_mem_pool_t.html", null ],
      [ "tinyxml2::MemPoolT< sizeof(tinyxml2::XMLElement) >", "classtinyxml2_1_1_mem_pool_t.html", null ],
      [ "tinyxml2::MemPoolT< sizeof(tinyxml2::XMLAttribute) >", "classtinyxml2_1_1_mem_pool_t.html", null ],
      [ "tinyxml2::MemPoolT< sizeof(tinyxml2::XMLText) >", "classtinyxml2_1_1_mem_pool_t.html", null ],
      [ "tinyxml2::MemPoolT< sizeof(tinyxml2::XMLComment) >", "classtinyxml2_1_1_mem_pool_t.html", null ],
      [ "tinyxml2::MemPoolT< ITEM_SIZE >", "classtinyxml2_1_1_mem_pool_t.html", null ],
      [ "tinyxml2::MemPoolT< ITEM_SIZE >", "classtinyxml2_1_1_mem_pool_t.html", null ]
    ] ],
    [ "server.model.Model", "classserver_1_1model_1_1_model.html", null ],
    [ "vision.utils.model_book.ModelBook", "classvision_1_1utils_1_1model__book_1_1_model_book.html", null ],
    [ "vision.prunning.prunner.ModelPrunner", "classvision_1_1prunning_1_1prunner_1_1_model_prunner.html", null ],
    [ "nn.Module", null, [
      [ "vision.nn.alexnet.AlexNet", "classvision_1_1nn_1_1alexnet_1_1_alex_net.html", null ],
      [ "vision.nn.mobilenet.MobileNetV1", "classvision_1_1nn_1_1mobilenet_1_1_mobile_net_v1.html", null ],
      [ "vision.nn.mobilenet_v2.InvertedResidual", "classvision_1_1nn_1_1mobilenet__v2_1_1_inverted_residual.html", null ],
      [ "vision.nn.mobilenet_v2.MobileNetV2", "classvision_1_1nn_1_1mobilenet__v2_1_1_mobile_net_v2.html", null ],
      [ "vision.nn.multibox_loss.MultiboxLoss", "classvision_1_1nn_1_1multibox__loss_1_1_multibox_loss.html", null ],
      [ "vision.nn.scaled_l2_norm.ScaledL2Norm", "classvision_1_1nn_1_1scaled__l2__norm_1_1_scaled_l2_norm.html", null ],
      [ "vision.nn.squeezenet.Fire", "classvision_1_1nn_1_1squeezenet_1_1_fire.html", null ],
      [ "vision.nn.squeezenet.SqueezeNet", "classvision_1_1nn_1_1squeezenet_1_1_squeeze_net.html", null ],
      [ "vision.ssd.fpn_ssd.FPNSSD", "classvision_1_1ssd_1_1fpn__ssd_1_1_f_p_n_s_s_d.html", null ],
      [ "vision.ssd.ssd.SSD", "classvision_1_1ssd_1_1ssd_1_1_s_s_d.html", null ]
    ] ],
    [ "Mutex", "class_mutex.html", null ],
    [ "NetworkInterface", "struct_network_interface.html", null ],
    [ "nlohmann::detail::nonesuch", "structnlohmann_1_1detail_1_1nonesuch.html", null ],
    [ "NvBufferCompositeBackground", "struct_nv_buffer_composite_background.html", null ],
    [ "NvBufferRect", "struct_nv_buffer_rect.html", null ],
    [ "object", null, [
      [ "datasets.cityscapes_utils.FilterAndRemapCityscapesCategories", "classdatasets_1_1cityscapes__utils_1_1_filter_and_remap_cityscapes_categories.html", null ],
      [ "datasets.coco_utils.ConvertCocoPolysToMask", "classdatasets_1_1coco__utils_1_1_convert_coco_polys_to_mask.html", null ],
      [ "datasets.coco_utils.FilterAndRemapCocoCategories", "classdatasets_1_1coco__utils_1_1_filter_and_remap_coco_categories.html", null ],
      [ "train.AverageMeter", "classtrain_1_1_average_meter.html", null ],
      [ "train.ProgressMeter", "classtrain_1_1_progress_meter.html", null ],
      [ "transforms.CenterCrop", "classtransforms_1_1_center_crop.html", null ],
      [ "transforms.Compose", "classtransforms_1_1_compose.html", null ],
      [ "transforms.Normalize", "classtransforms_1_1_normalize.html", null ],
      [ "transforms.RandomCrop", "classtransforms_1_1_random_crop.html", null ],
      [ "transforms.RandomHorizontalFlip", "classtransforms_1_1_random_horizontal_flip.html", null ],
      [ "transforms.RandomResize", "classtransforms_1_1_random_resize.html", null ],
      [ "transforms.Resize", "classtransforms_1_1_resize.html", null ],
      [ "transforms.ToTensor", "classtransforms_1_1_to_tensor.html", null ],
      [ "utils.ConfusionMatrix", "classutils_1_1_confusion_matrix.html", null ],
      [ "utils.MetricLogger", "classutils_1_1_metric_logger.html", null ],
      [ "utils.SmoothedValue", "classutils_1_1_smoothed_value.html", null ],
      [ "vision.ssd.fpn_ssd.MatchPrior", "classvision_1_1ssd_1_1fpn__ssd_1_1_match_prior.html", null ],
      [ "vision.ssd.ssd.MatchPrior", "classvision_1_1ssd_1_1ssd_1_1_match_prior.html", null ],
      [ "vision.transforms.transforms.Compose", "classvision_1_1transforms_1_1transforms_1_1_compose.html", null ],
      [ "vision.transforms.transforms.ConvertColor", "classvision_1_1transforms_1_1transforms_1_1_convert_color.html", null ],
      [ "vision.transforms.transforms.ConvertFromInts", "classvision_1_1transforms_1_1transforms_1_1_convert_from_ints.html", null ],
      [ "vision.transforms.transforms.Expand", "classvision_1_1transforms_1_1transforms_1_1_expand.html", null ],
      [ "vision.transforms.transforms.Lambda", "classvision_1_1transforms_1_1transforms_1_1_lambda.html", null ],
      [ "vision.transforms.transforms.PhotometricDistort", "classvision_1_1transforms_1_1transforms_1_1_photometric_distort.html", null ],
      [ "vision.transforms.transforms.RandomBrightness", "classvision_1_1transforms_1_1transforms_1_1_random_brightness.html", null ],
      [ "vision.transforms.transforms.RandomContrast", "classvision_1_1transforms_1_1transforms_1_1_random_contrast.html", null ],
      [ "vision.transforms.transforms.RandomHue", "classvision_1_1transforms_1_1transforms_1_1_random_hue.html", null ],
      [ "vision.transforms.transforms.RandomLightingNoise", "classvision_1_1transforms_1_1transforms_1_1_random_lighting_noise.html", null ],
      [ "vision.transforms.transforms.RandomMirror", "classvision_1_1transforms_1_1transforms_1_1_random_mirror.html", null ],
      [ "vision.transforms.transforms.RandomSampleCrop", "classvision_1_1transforms_1_1transforms_1_1_random_sample_crop.html", null ],
      [ "vision.transforms.transforms.RandomSaturation", "classvision_1_1transforms_1_1transforms_1_1_random_saturation.html", null ],
      [ "vision.transforms.transforms.Resize", "classvision_1_1transforms_1_1transforms_1_1_resize.html", null ],
      [ "vision.transforms.transforms.SubtractMeans", "classvision_1_1transforms_1_1transforms_1_1_subtract_means.html", null ],
      [ "vision.transforms.transforms.SwapChannels", "classvision_1_1transforms_1_1transforms_1_1_swap_channels.html", null ],
      [ "vision.transforms.transforms.ToAbsoluteCoords", "classvision_1_1transforms_1_1transforms_1_1_to_absolute_coords.html", null ],
      [ "vision.transforms.transforms.ToCV2Image", "classvision_1_1transforms_1_1transforms_1_1_to_c_v2_image.html", null ],
      [ "vision.transforms.transforms.ToPercentCoords", "classvision_1_1transforms_1_1transforms_1_1_to_percent_coords.html", null ],
      [ "vision.transforms.transforms.ToTensor", "classvision_1_1transforms_1_1transforms_1_1_to_tensor.html", null ]
    ] ],
    [ "poseNet::ObjectPose", "structpose_net_1_1_object_pose.html", null ],
    [ "objectTracker", "classobject_tracker.html", [
      [ "objectTrackerIOU", "classobject_tracker_i_o_u.html", null ]
    ] ],
    [ "vision.datasets.open_images.OpenImagesDataset", "classvision_1_1datasets_1_1open__images_1_1_open_images_dataset.html", null ],
    [ "nlohmann::ordered_map&lt; Key, T, IgnoredLess, Allocator &gt;", "structnlohmann_1_1ordered__map.html", null ],
    [ "nlohmann::detail::output_adapter&lt; CharType, StringType &gt;", "classnlohmann_1_1detail_1_1output__adapter.html", null ],
    [ "nlohmann::detail::output_adapter_protocol&lt; CharType &gt;", "structnlohmann_1_1detail_1_1output__adapter__protocol.html", [
      [ "nlohmann::detail::output_stream_adapter< CharType >", "classnlohmann_1_1detail_1_1output__stream__adapter.html", null ],
      [ "nlohmann::detail::output_stream_adapter< CharType >", "classnlohmann_1_1detail_1_1output__stream__adapter.html", null ],
      [ "nlohmann::detail::output_string_adapter< CharType, StringType >", "classnlohmann_1_1detail_1_1output__string__adapter.html", null ],
      [ "nlohmann::detail::output_string_adapter< CharType, StringType >", "classnlohmann_1_1detail_1_1output__string__adapter.html", null ],
      [ "nlohmann::detail::output_vector_adapter< CharType >", "classnlohmann_1_1detail_1_1output__vector__adapter.html", null ],
      [ "nlohmann::detail::output_vector_adapter< CharType >", "classnlohmann_1_1detail_1_1output__vector__adapter.html", null ]
    ] ],
    [ "dashboard.ParkingDashboard", "classdashboard_1_1_parking_dashboard.html", null ],
    [ "nlohmann::detail::parser&lt; BasicJsonType, InputAdapterType &gt;", "classnlohmann_1_1detail_1_1parser.html", null ],
    [ "gstWebRTC::PeerContext", "structgst_web_r_t_c_1_1_peer_context.html", null ],
    [ "ocr_pipeline.PlateOcrPipeline", "classocr__pipeline_1_1_plate_ocr_pipeline.html", null ],
    [ "PointVertex", "struct_point_vertex.html", null ],
    [ "nlohmann::detail::position_t", "structnlohmann_1_1detail_1_1position__t.html", null ],
    [ "vision.ssd.data_preprocessing.PredictionTransform", "classvision_1_1ssd_1_1data__preprocessing_1_1_prediction_transform.html", null ],
    [ "vision.ssd.predictor.Predictor", "classvision_1_1ssd_1_1predictor_1_1_predictor.html", null ],
    [ "nlohmann::detail::primitive_iterator_t", "classnlohmann_1_1detail_1_1primitive__iterator__t.html", null ],
    [ "nlohmann::detail::priority_tag&lt; N &gt;", "structnlohmann_1_1detail_1_1priority__tag.html", null ],
    [ "nlohmann::detail::priority_tag&lt; 0 &gt;", "structnlohmann_1_1detail_1_1priority__tag_3_010_01_4.html", null ],
    [ "Process", "class_process.html", null ],
    [ "PyActionNet_Object", "struct_py_action_net___object.html", null ],
    [ "PyBackgroundNet_Object", "struct_py_background_net___object.html", null ],
    [ "PyCamera_Object", "struct_py_camera___object.html", null ],
    [ "PyCudaImage", "struct_py_cuda_image.html", null ],
    [ "PyCudaMemory", "struct_py_cuda_memory.html", null ],
    [ "PyDepthNet_Object", "struct_py_depth_net___object.html", null ],
    [ "PyDetection_Object", "struct_py_detection___object.html", null ],
    [ "PyDetectNet_Object", "struct_py_detect_net___object.html", null ],
    [ "PyDisplay_Object", "struct_py_display___object.html", null ],
    [ "PyFont_Object", "struct_py_font___object.html", null ],
    [ "PyImageNet_Object", "struct_py_image_net___object.html", null ],
    [ "PyLogging_Object", "struct_py_logging___object.html", null ],
    [ "PyObjectPose_Object", "struct_py_object_pose___object.html", null ],
    [ "PyPoseKeypoint_Object", "struct_py_pose_keypoint___object.html", null ],
    [ "PyPoseNet_Object", "struct_py_pose_net___object.html", null ],
    [ "PySegNet_Object", "struct_py_seg_net___object.html", null ],
    [ "PyTensorNet_Object", "struct_py_tensor_net___object.html", null ],
    [ "PyVideoOutput_Object", "struct_py_video_output___object.html", null ],
    [ "PyVideoSource_Object", "struct_py_video_source___object.html", null ],
    [ "qt_meta_stringdata_ControlClassifyWidget_t", "structqt__meta__stringdata___control_classify_widget__t.html", null ],
    [ "qt_meta_stringdata_ControlDetectionWidget_t", "structqt__meta__stringdata___control_detection_widget__t.html", null ],
    [ "qt_meta_stringdata_ControlWindow_t", "structqt__meta__stringdata___control_window__t.html", null ],
    [ "std::reverse_iterator", null, [
      [ "nlohmann::detail::json_reverse_iterator< typename basic_json::iterator >", "classnlohmann_1_1detail_1_1json__reverse__iterator.html", null ],
      [ "nlohmann::detail::json_reverse_iterator< typename basic_json::const_iterator >", "classnlohmann_1_1detail_1_1json__reverse__iterator.html", null ],
      [ "nlohmann::detail::json_reverse_iterator< typename basic_json::iterator >", "classnlohmann_1_1detail_1_1json__reverse__iterator.html", null ],
      [ "nlohmann::detail::json_reverse_iterator< typename basic_json::const_iterator >", "classnlohmann_1_1detail_1_1json__reverse__iterator.html", null ],
      [ "nlohmann::detail::json_reverse_iterator< Base >", "classnlohmann_1_1detail_1_1json__reverse__iterator.html", null ],
      [ "nlohmann::detail::json_reverse_iterator< Base >", "classnlohmann_1_1detail_1_1json__reverse__iterator.html", null ]
    ] ],
    [ "RingBuffer", "class_ring_buffer.html", null ],
    [ "RTSPServer", "class_r_t_s_p_server.html", null ],
    [ "segnet_utils.segmentationBuffers", "classsegnet__utils_1_1segmentation_buffers.html", null ],
    [ "nlohmann::detail::serializer&lt; BasicJsonType &gt;", "classnlohmann_1_1detail_1_1serializer.html", null ],
    [ "server.server.Server", "classserver_1_1server_1_1_server.html", null ],
    [ "Socket", "class_socket.html", null ],
    [ "nlohmann::detail::span_input_adapter", "classnlohmann_1_1detail_1_1span__input__adapter.html", null ],
    [ "nlohmann::detail::static_const&lt; T &gt;", "structnlohmann_1_1detail_1_1static__const.html", null ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", null ],
    [ "stbtt__bitmap", "structstbtt____bitmap.html", null ],
    [ "stbtt__buf", "structstbtt____buf.html", null ],
    [ "stbtt_aligned_quad", "structstbtt__aligned__quad.html", null ],
    [ "stbtt_bakedchar", "structstbtt__bakedchar.html", null ],
    [ "stbtt_fontinfo", "structstbtt__fontinfo.html", null ],
    [ "stbtt_pack_context", "structstbtt__pack__context.html", null ],
    [ "stbtt_pack_range", "structstbtt__pack__range.html", null ],
    [ "stbtt_packedchar", "structstbtt__packedchar.html", null ],
    [ "stbtt_vertex", "structstbtt__vertex.html", null ],
    [ "server.stream.Stream", "classserver_1_1stream_1_1_stream.html", null ],
    [ "tinyxml2::StrPair", "classtinyxml2_1_1_str_pair.html", null ],
    [ "tensorNet", "classtensor_net.html", [
      [ "actionNet", "classaction_net.html", null ],
      [ "backgroundNet", "classbackground_net.html", null ],
      [ "depthNet", "classdepth_net.html", null ],
      [ "detectNet", "classdetect_net.html", null ],
      [ "imageNet", "classimage_net.html", null ],
      [ "poseNet", "classpose_net.html", null ],
      [ "segNet", "classseg_net.html", null ]
    ] ],
    [ "vision.ssd.data_preprocessing.TestTransform", "classvision_1_1ssd_1_1data__preprocessing_1_1_test_transform.html", null ],
    [ "Thread", "class_thread.html", null ],
    [ "threading.Thread", null, [
      [ "dataset.Dataset", "classdataset_1_1_dataset.html", null ],
      [ "model.Model", "classmodel_1_1_model.html", null ],
      [ "stream.Stream", "classstream_1_1_stream.html", null ],
      [ "stream.Stream", "classstream_1_1_stream.html", null ],
      [ "stream.Stream", "classstream_1_1_stream.html", null ]
    ] ],
    [ "vision.utils.misc.Timer", "classvision_1_1utils_1_1misc_1_1_timer.html", null ],
    [ "nlohmann::detail::to_json_fn", "structnlohmann_1_1detail_1_1to__json__fn.html", null ],
    [ "poseNet::Topology", "structpose_net_1_1_topology.html", null ],
    [ "vision.ssd.data_preprocessing.TrainAugmentation", "classvision_1_1ssd_1_1data__preprocessing_1_1_train_augmentation.html", null ],
    [ "std::true_type", null, [
      [ "nlohmann::detail::conjunction< is_constructible< T1, Args >... >", "structnlohmann_1_1detail_1_1conjunction.html", [
        [ "nlohmann::detail::is_constructible_tuple< T1, std::tuple< Args... > >", "structnlohmann_1_1detail_1_1is__constructible__tuple_3_01_t1_00_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ],
        [ "nlohmann::detail::is_constructible_tuple< T1, std::tuple< Args... > >", "structnlohmann_1_1detail_1_1is__constructible__tuple_3_01_t1_00_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ]
      ] ],
      [ "nlohmann::detail::conjunction< is_default_constructible< T1 >, is_default_constructible< T2 > >", "structnlohmann_1_1detail_1_1conjunction.html", [
        [ "nlohmann::detail::is_default_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "nlohmann::detail::is_default_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "nlohmann::detail::is_default_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "nlohmann::detail::is_default_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ]
      ] ],
      [ "nlohmann::detail::conjunction< is_default_constructible< Ts >... >", "structnlohmann_1_1detail_1_1conjunction.html", [
        [ "nlohmann::detail::is_default_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "nlohmann::detail::is_default_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "nlohmann::detail::is_default_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "nlohmann::detail::is_default_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ]
      ] ],
      [ "nlohmann::detail::conjunction< B1 >", "structnlohmann_1_1detail_1_1conjunction_3_01_b1_01_4.html", null ],
      [ "nlohmann::detail::conjunction< B1, Bn... >", "structnlohmann_1_1detail_1_1conjunction_3_01_b1_00_01_bn_8_8_8_01_4.html", null ],
      [ "nlohmann::detail::conjunction< is_constructible< T1, Args >... >", "structnlohmann_1_1detail_1_1conjunction.html", null ],
      [ "nlohmann::detail::conjunction< is_default_constructible< T1 >, is_default_constructible< T2 > >", "structnlohmann_1_1detail_1_1conjunction.html", null ],
      [ "nlohmann::detail::conjunction< is_default_constructible< Ts >... >", "structnlohmann_1_1detail_1_1conjunction.html", null ],
      [ "nlohmann::detail::conjunction< B1 >", "structnlohmann_1_1detail_1_1conjunction_3_01_b1_01_4.html", null ],
      [ "nlohmann::detail::conjunction< B1, Bn... >", "structnlohmann_1_1detail_1_1conjunction_3_01_b1_00_01_bn_8_8_8_01_4.html", null ],
      [ "nlohmann::detail::conjunction<... >", "structnlohmann_1_1detail_1_1conjunction.html", null ],
      [ "nlohmann::detail::conjunction<... >", "structnlohmann_1_1detail_1_1conjunction.html", null ],
      [ "nlohmann::detail::is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "structnlohmann_1_1detail_1_1is__basic__json_3_01_n_l_o_h_m_a_n_n___b_a_s_i_c___j_s_o_n___t_p_l_01_4.html", null ],
      [ "nlohmann::detail::is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "structnlohmann_1_1detail_1_1is__basic__json_3_01_n_l_o_h_m_a_n_n___b_a_s_i_c___j_s_o_n___t_p_l_01_4.html", null ],
      [ "nlohmann::detail::is_complete_type< T, decltype(void(sizeof(T)))>", "structnlohmann_1_1detail_1_1is__complete__type_3_01_t_00_01decltype_07void_07sizeof_07_t_08_08_08_4.html", null ],
      [ "nlohmann::detail::is_complete_type< T, decltype(void(sizeof(T)))>", "structnlohmann_1_1detail_1_1is__complete__type_3_01_t_00_01decltype_07void_07sizeof_07_t_08_08_08_4.html", null ],
      [ "nlohmann::detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_cons8cf88e17d5eaa68665a8fb4b97604b0e.html", null ],
      [ "nlohmann::detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_cons8cf88e17d5eaa68665a8fb4b97604b0e.html", null ],
      [ "nlohmann::detail::is_json_ref< json_ref< T > >", "structnlohmann_1_1detail_1_1is__json__ref_3_01json__ref_3_01_t_01_4_01_4.html", null ],
      [ "nlohmann::detail::is_json_ref< json_ref< T > >", "structnlohmann_1_1detail_1_1is__json__ref_3_01json__ref_3_01_t_01_4_01_4.html", null ]
    ] ],
    [ "std::tuple_element&lt; N, ::nlohmann::detail::iteration_proxy_value&lt; IteratorType &gt; &gt;", "classstd_1_1tuple__element_3_01_n_00_01_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01_iterator_type_01_4_01_4.html", null ],
    [ "std::conditional::type", null, [
      [ "nlohmann::detail::conjunction< B1, Bn... >", "structnlohmann_1_1detail_1_1conjunction_3_01_b1_00_01_bn_8_8_8_01_4.html", null ],
      [ "nlohmann::detail::conjunction< B1, Bn... >", "structnlohmann_1_1detail_1_1conjunction_3_01_b1_00_01_bn_8_8_8_01_4.html", null ]
    ] ],
    [ "URI", "struct_u_r_i.html", null ],
    [ "v4l2Camera", "classv4l2_camera.html", null ],
    [ "cudaPointCloud::Vertex", "structcuda_point_cloud_1_1_vertex.html", null ],
    [ "videoOptions", "structvideo_options.html", null ],
    [ "videoOutput", "classvideo_output.html", [
      [ "glDisplay", "classgl_display.html", null ],
      [ "glDisplay", "classgl_display.html", null ],
      [ "gstEncoder", "classgst_encoder.html", null ],
      [ "gstEncoder", "classgst_encoder.html", null ],
      [ "imageWriter", "classimage_writer.html", null ],
      [ "imageWriter", "classimage_writer.html", null ]
    ] ],
    [ "videoSource", "classvideo_source.html", [
      [ "gstCamera", "classgst_camera.html", null ],
      [ "gstCamera", "classgst_camera.html", null ],
      [ "gstDecoder", "classgst_decoder.html", null ],
      [ "gstDecoder", "classgst_decoder.html", null ],
      [ "imageLoader", "classimage_loader.html", null ],
      [ "imageLoader", "classimage_loader.html", null ]
    ] ],
    [ "WebRTCPeer", "struct_web_r_t_c_peer.html", null ],
    [ "WebRTCServer", "class_web_r_t_c_server.html", null ],
    [ "WebRTCServer::WebsocketRoute", "struct_web_r_t_c_server_1_1_websocket_route.html", null ],
    [ "nlohmann::detail::wide_string_input_adapter&lt; BaseInputAdapter, WideCharType &gt;", "classnlohmann_1_1detail_1_1wide__string__input__adapter.html", null ],
    [ "nlohmann::detail::wide_string_input_helper&lt; BaseInputAdapter, T &gt;", "structnlohmann_1_1detail_1_1wide__string__input__helper.html", null ],
    [ "nlohmann::detail::wide_string_input_helper&lt; BaseInputAdapter, 2 &gt;", "structnlohmann_1_1detail_1_1wide__string__input__helper_3_01_base_input_adapter_00_012_01_4.html", null ],
    [ "nlohmann::detail::wide_string_input_helper&lt; BaseInputAdapter, 4 &gt;", "structnlohmann_1_1detail_1_1wide__string__input__helper_3_01_base_input_adapter_00_014_01_4.html", null ],
    [ "tinyxml2::XMLAttribute", "classtinyxml2_1_1_x_m_l_attribute.html", null ],
    [ "tinyxml2::XMLConstHandle", "classtinyxml2_1_1_x_m_l_const_handle.html", null ],
    [ "tinyxml2::XMLHandle", "classtinyxml2_1_1_x_m_l_handle.html", null ],
    [ "tinyxml2::XMLNode", "classtinyxml2_1_1_x_m_l_node.html", [
      [ "tinyxml2::XMLComment", "classtinyxml2_1_1_x_m_l_comment.html", null ],
      [ "tinyxml2::XMLComment", "classtinyxml2_1_1_x_m_l_comment.html", null ],
      [ "tinyxml2::XMLDeclaration", "classtinyxml2_1_1_x_m_l_declaration.html", null ],
      [ "tinyxml2::XMLDeclaration", "classtinyxml2_1_1_x_m_l_declaration.html", null ],
      [ "tinyxml2::XMLDocument", "classtinyxml2_1_1_x_m_l_document.html", null ],
      [ "tinyxml2::XMLDocument", "classtinyxml2_1_1_x_m_l_document.html", null ],
      [ "tinyxml2::XMLElement", "classtinyxml2_1_1_x_m_l_element.html", null ],
      [ "tinyxml2::XMLElement", "classtinyxml2_1_1_x_m_l_element.html", null ],
      [ "tinyxml2::XMLText", "classtinyxml2_1_1_x_m_l_text.html", null ],
      [ "tinyxml2::XMLText", "classtinyxml2_1_1_x_m_l_text.html", null ],
      [ "tinyxml2::XMLUnknown", "classtinyxml2_1_1_x_m_l_unknown.html", null ],
      [ "tinyxml2::XMLUnknown", "classtinyxml2_1_1_x_m_l_unknown.html", null ]
    ] ],
    [ "tinyxml2::XMLUtil", "classtinyxml2_1_1_x_m_l_util.html", null ],
    [ "tinyxml2::XMLVisitor", "classtinyxml2_1_1_x_m_l_visitor.html", [
      [ "tinyxml2::XMLPrinter", "classtinyxml2_1_1_x_m_l_printer.html", null ],
      [ "tinyxml2::XMLPrinter", "classtinyxml2_1_1_x_m_l_printer.html", null ]
    ] ]
];