var searchData=
[
  ['javascript_0',['HTML / JavaScript',['../md_jetson-inference_2docs_2webrtc-html.html#autotoc_md439',1,'']]],
  ['jetpack_1',['JetPack',['../md_jetson-inference_2docs_2jetpack-setup-2.html#autotoc_md328',1,'Setting up Jetson with JetPack'],['../md_jetson-inference_2docs_2jetpack-setup.html#autotoc_md333',1,'Setting up Jetson with JetPack']]],
  ['jetpack_20setup_2',['jetpack-setup',['../md_jetson-inference_2docs_2jetpack-setup.html',1,'']]],
  ['jetpack_20setup_202_3',['jetpack-setup-2',['../md_jetson-inference_2docs_2jetpack-setup-2.html',1,'']]],
  ['jetson_4',['Jetson',['../md_jetson-inference_2docs_2imagenet-snapshot.html#autotoc_md315',1,'Downloading Model Snapshots to Jetson'],['../md_jetson-inference_2docs_2detectnet-snapshot.html#autotoc_md209',1,'Downloading the Detection Model to Jetson'],['../md_jetson-inference_2docs_2imagenet-custom.html#autotoc_md274',1,'Loading Custom Models on Jetson'],['../md_jetson-inference_2docs_2segnet-console.html#autotoc_md413',1,'Running Segmentation Models on Jetson'],['../md_jetson-inference_2docs_2imagenet-console.html#autotoc_md266',1,'Using the Console Program on Jetson'],['../md_jetson-inference_2docs_2imagenet-console-2.html#autotoc_md260',1,'Using the ImageNet Program on Jetson']]],
  ['jetson_20ai_20lab_5',['Jetson AI Lab',['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md475',1,'']]],
  ['jetson_20inference_6',['jetson inference',['../group__deep_vision.html',1,'DNN Vision Library (jetson-inference)'],['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md478',1,'jetson-inference']]],
  ['jetson_20license_20plate_20recognition_7',['Jetson License Plate Recognition',['../md__r_e_a_d_m_e.html',1,'']]],
  ['jetson_20nano_20orin_20nano_20and_20xavier_20nx_8',['Jetson Nano, Orin Nano, and Xavier NX',['../md_jetson-inference_2docs_2jetpack-setup-2.html#autotoc_md329',1,'']]],
  ['jetson_20tx1_20tx2_20agx_20xavier_20and_20agx_20orin_9',['Jetson TX1/TX2, AGX Xavier, and AGX Orin',['../md_jetson-inference_2docs_2jetpack-setup-2.html#autotoc_md330',1,'']]],
  ['jetson_20utils_10',['jetson utils',['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md479',1,'jetson-utils'],['../dir_24f5d2e6f66986322dddc02d8dd8aa7a.html#autotoc_md519',1,'jetson-utils'],['../group__util.html',1,'Utilities Library (jetson-utils)']]],
  ['jetson_20with_20jetpack_11',['Jetson with JetPack',['../md_jetson-inference_2docs_2jetpack-setup-2.html#autotoc_md328',1,'Setting up Jetson with JetPack'],['../md_jetson-inference_2docs_2jetpack-setup.html#autotoc_md333',1,'Setting up Jetson with JetPack']]],
  ['job_20directories_12',['Setting up data and job directories',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md246',1,'']]],
  ['job_20directory_20for_20digits_13',['Setting up data and job directory for DIGITS',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md245',1,'']]],
  ['joystickdevice_14',['JoystickDevice',['../class_joystick_device.html',1,'']]],
  ['json_15',['json',['../namespacenlohmann.html#a8ba8c5483f73a36e716558571ff97d57',1,'nlohmann']]],
  ['json_5fpointer_16',['json_pointer',['../classnlohmann_1_1json__pointer.html',1,'nlohmann::json_pointer&lt; BasicJsonType &gt;'],['../classnlohmann_1_1json__pointer.html#a7f32d7c62841f0c4a6784cf741a6e4f8',1,'nlohmann::json_pointer::json_pointer(const std::string &amp;s=&quot;&quot;)'],['../classnlohmann_1_1json__pointer.html#a7f32d7c62841f0c4a6784cf741a6e4f8',1,'nlohmann::json_pointer::json_pointer(const std::string &amp;s=&quot;&quot;)']]],
  ['json_5fpointer_3c_20basic_5fjson_20_3e_17',['json_pointer&lt; basic_json &gt;',['../classnlohmann_1_1json__pointer.html',1,'nlohmann']]],
  ['json_5fref_18',['json_ref',['../classnlohmann_1_1detail_1_1json__ref.html',1,'nlohmann::detail']]],
  ['json_5freverse_5fiterator_19',['json_reverse_iterator',['../classnlohmann_1_1detail_1_1json__reverse__iterator.html',1,'nlohmann::detail']]],
  ['json_5freverse_5fiterator_3c_20typename_20basic_5fjson_3a_3aconst_5fiterator_20_3e_20',['json_reverse_iterator&lt; typename basic_json::const_iterator &gt;',['../classnlohmann_1_1detail_1_1json__reverse__iterator.html',1,'nlohmann::detail']]],
  ['json_5freverse_5fiterator_3c_20typename_20basic_5fjson_3a_3aiterator_20_3e_21',['json_reverse_iterator&lt; typename basic_json::iterator &gt;',['../classnlohmann_1_1detail_1_1json__reverse__iterator.html',1,'nlohmann::detail']]],
  ['json_5fsax_22',['json_sax',['../structnlohmann_1_1json__sax.html',1,'nlohmann']]],
  ['json_5fsax_3c_20basic_5fjson_20_3e_23',['json_sax&lt; basic_json &gt;',['../structnlohmann_1_1json__sax.html',1,'nlohmann']]],
  ['json_5fsax_5facceptor_24',['json_sax_acceptor',['../classnlohmann_1_1detail_1_1json__sax__acceptor.html',1,'nlohmann::detail']]],
  ['json_5fsax_5fdom_5fcallback_5fparser_25',['json_sax_dom_callback_parser',['../classnlohmann_1_1detail_1_1json__sax__dom__callback__parser.html',1,'nlohmann::detail']]],
  ['json_5fsax_5fdom_5fparser_26',['json_sax_dom_parser',['../classnlohmann_1_1detail_1_1json__sax__dom__parser.html',1,'nlohmann::detail::json_sax_dom_parser&lt; BasicJsonType &gt;'],['../classnlohmann_1_1detail_1_1json__sax__dom__parser.html#afc50fee0a92ce84afb84041ebbdfba80',1,'nlohmann::detail::json_sax_dom_parser::json_sax_dom_parser(BasicJsonType &amp;r, const bool allow_exceptions_=true)'],['../classnlohmann_1_1detail_1_1json__sax__dom__parser.html#afc50fee0a92ce84afb84041ebbdfba80',1,'nlohmann::detail::json_sax_dom_parser::json_sax_dom_parser(BasicJsonType &amp;r, const bool allow_exceptions_=true)']]],
  ['json_5fstr_27',['JSON_STR',['../group__model_downloader.html#ga61fe6cb2e130091e0e33a81e8cca43d2',1,'modelDownloader.h']]],
  ['json_5fstr_5fdefault_28',['JSON_STR_DEFAULT',['../group__model_downloader.html#gade5ee56e8f8bf404fcd9dd17e98c54e2',1,'modelDownloader.h']]]
];
