var searchData=
[
  ['a_20demo_20digits_0',['Two Days to a Demo (DIGITS)',['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md489',1,'']]],
  ['a_20directory_20or_20sequence_20of_20images_1',['a Directory or Sequence of Images',['../md_jetson-inference_2docs_2detectnet-console-2.html#autotoc_md184',1,'Processing a Directory or Sequence of Images'],['../md_jetson-inference_2docs_2segnet-console-2.html#autotoc_md411',1,'Processing a Directory or Sequence of Images']]],
  ['a_20numpy_20array_2',['Accessing as a Numpy Array',['../md_jetson-inference_2docs_2aux-image.html#autotoc_md69',1,'']]],
  ['a_20object_20detection_20yolov8_3',['A. Object Detection (YOLOv8)',['../md_about.html#autotoc_md6',1,'']]],
  ['a_20pretrained_20model_4',['Launching With a Pretrained Model',['../md_jetson-inference_2docs_2detectnet-console.html#autotoc_md191',1,'']]],
  ['a_20video_5',['Processing a Video',['../md_jetson-inference_2docs_2imagenet-console-2.html#autotoc_md263',1,'']]],
  ['about_20this_20project_6',['About This Project',['../md_about.html',1,'']]],
  ['accessing_20as_20a_20numpy_20array_7',['Accessing as a Numpy Array',['../md_jetson-inference_2docs_2aux-image.html#autotoc_md69',1,'']]],
  ['accessing_20image_20data_20in_20python_8',['Accessing Image Data in Python',['../md_jetson-inference_2docs_2aux-image.html#autotoc_md68',1,'']]],
  ['accuracy_9',['Accuracy',['../md_jetson-inference_2docs_2pytorch-cat-dog.html#autotoc_md352',1,'Model Accuracy'],['../md_jetson-inference_2docs_2pytorch-plants.html#autotoc_md371',1,'Model Accuracy']]],
  ['action_20recognition_10',['Action Recognition',['../md_jetson-inference_2docs_2actionnet.html#autotoc_md42',1,'Action Recognition'],['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md486',1,'Action Recognition']]],
  ['action_20recognition_20models_11',['Pre-trained Action Recognition Models',['../md_jetson-inference_2docs_2actionnet.html#autotoc_md45',1,'']]],
  ['actionnet_12',['actionnet',['../md_jetson-inference_2docs_2actionnet.html',1,'']]],
  ['actions_13',['Actions',['../md_jetson-inference_2docs_2webrtc-dash.html#autotoc_md432',1,'']]],
  ['aerial_20dataset_20into_20digits_14',['Importing the Aerial Dataset into DIGITS',['../md_jetson-inference_2docs_2segnet-dataset.html#autotoc_md417',1,'']]],
  ['aerial_20drone_20dataset_15',['Downloading Aerial Drone Dataset',['../md_jetson-inference_2docs_2segnet-dataset.html#autotoc_md416',1,'']]],
  ['agx_20orin_16',['Jetson TX1/TX2, AGX Xavier, and AGX Orin',['../md_jetson-inference_2docs_2jetpack-setup-2.html#autotoc_md330',1,'']]],
  ['agx_20xavier_20and_20agx_20orin_17',['Jetson TX1/TX2, AGX Xavier, and AGX Orin',['../md_jetson-inference_2docs_2jetpack-setup-2.html#autotoc_md330',1,'']]],
  ['ai_20lab_18',['Jetson AI Lab',['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md475',1,'']]],
  ['ai_20world_19',['Hello AI World',['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md469',1,'']]],
  ['alexnet_20',['Generating Pretrained FCN-Alexnet',['../md_jetson-inference_2docs_2segnet-pretrained.html#autotoc_md421',1,'']]],
  ['alexnet_20patches_20for_20tensorrt_21',['FCN-Alexnet Patches for TensorRT',['../md_jetson-inference_2docs_2segnet-patches.html#autotoc_md419',1,'']]],
  ['alexnet_20with_20digits_22',['Training FCN-Alexnet with DIGITS',['../md_jetson-inference_2docs_2segnet-training.html#autotoc_md423',1,'']]],
  ['algorithms_23',['4. Application Logic &amp;amp; Algorithms',['../md_about.html#autotoc_md9',1,'']]],
  ['all_20the_20test_20images_24',['all the Test Images',['../md_jetson-inference_2docs_2pytorch-cat-dog.html#autotoc_md355',1,'Processing all the Test Images'],['../md_jetson-inference_2docs_2pytorch-plants.html#autotoc_md374',1,'Processing all the Test Images']]],
  ['allocation_25',['Image Allocation',['../md_jetson-inference_2docs_2aux-image.html#autotoc_md60',1,'']]],
  ['amount_20of_20data_26',['Limiting the Amount of Data',['../md_jetson-inference_2docs_2pytorch-ssd.html#autotoc_md379',1,'']]],
  ['and_20agx_20orin_27',['Jetson TX1/TX2, AGX Xavier, and AGX Orin',['../md_jetson-inference_2docs_2jetpack-setup-2.html#autotoc_md330',1,'']]],
  ['and_20job_20directories_28',['Setting up data and job directories',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md246',1,'']]],
  ['and_20job_20directory_20for_20digits_29',['Setting up data and job directory for DIGITS',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md245',1,'']]],
  ['and_20multimedia_30',['Camera Streaming and Multimedia',['../md_jetson-inference_2docs_2aux-streaming.html#autotoc_md93',1,'']]],
  ['and_20parsing_20the_20command_20line_31',['and Parsing the Command Line',['../md_jetson-inference_2docs_2imagenet-example-2.html#autotoc_md280',1,'Declaring main() and Parsing the Command Line'],['../md_jetson-inference_2docs_2imagenet-example.html#autotoc_md305',1,'Declaring main() and Parsing the Command Line']]],
  ['and_20xavier_20nx_32',['Jetson Nano, Orin Nano, and Xavier NX',['../md_jetson-inference_2docs_2jetpack-setup-2.html#autotoc_md329',1,'']]],
  ['api_20reference_33',['API Reference',['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md477',1,'']]],
  ['appendix_34',['Appendix',['../md_jetson-inference_2docs_2aux-contents.html#autotoc_md47',1,'Appendix'],['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md474',1,'Appendix']]],
  ['application_20logic_20algorithms_35',['4. Application Logic &amp;amp; Algorithms',['../md_about.html#autotoc_md9',1,'']]],
  ['applications_36',['Running Applications',['../md_jetson-inference_2docs_2aux-docker.html#autotoc_md54',1,'']]],
  ['arguments_37',['Arguments',['../md_jetson-inference_2docs_2actionnet.html#autotoc_md44',1,'Command-Line Arguments'],['../md_jetson-inference_2docs_2aux-streaming.html#autotoc_md96',1,'Command-Line Arguments']]],
  ['array_38',['Accessing as a Numpy Array',['../md_jetson-inference_2docs_2aux-image.html#autotoc_md69',1,'']]],
  ['array_20interface_39',['CUDA Array Interface',['../md_jetson-inference_2docs_2aux-image.html#autotoc_md72',1,'']]],
  ['array_20interfaces_40',['Array Interfaces',['../md_jetson-inference_2docs_2aux-image.html#autotoc_md67',1,'']]],
  ['arrays_41',['Arrays',['../md_jetson-inference_2docs_2aux-image.html#autotoc_md71',1,'Converting from Numpy Arrays'],['../md_jetson-inference_2docs_2aux-image.html#autotoc_md70',1,'Converting to Numpy Arrays']]],
  ['as_20a_20numpy_20array_42',['Accessing as a Numpy Array',['../md_jetson-inference_2docs_2aux-image.html#autotoc_md69',1,'']]],
  ['aux_20contents_43',['aux-contents',['../md_jetson-inference_2docs_2aux-contents.html',1,'']]],
  ['aux_20docker_44',['aux-docker',['../md_jetson-inference_2docs_2aux-docker.html',1,'']]],
  ['aux_20image_45',['aux-image',['../md_jetson-inference_2docs_2aux-image.html',1,'']]],
  ['aux_20streaming_46',['aux-streaming',['../md_jetson-inference_2docs_2aux-streaming.html',1,'']]],
  ['available_47',['Available',['../md_jetson-inference_2docs_2detectnet-console-2.html#autotoc_md186',1,'Pre-trained Detection Models Available'],['../md_jetson-inference_2docs_2detectnet-console.html#autotoc_md194',1,'Pre-trained Detection Models Available'],['../md_jetson-inference_2docs_2segnet-console-2.html#autotoc_md397',1,'Pre-Trained Segmentation Models Available']]]
];
