var searchData=
[
  ['d_0',['SUN RGB-D',['../md_jetson-inference_2docs_2segnet-console-2.html#autotoc_md409',1,'']]],
  ['dash_1',['webrtc-dash',['../md_jetson-inference_2docs_2webrtc-dash.html',1,'']]],
  ['dashboard_2',['Plotly Dashboard',['../md_jetson-inference_2docs_2webrtc-dash.html#autotoc_md426',1,'']]],
  ['dashcamnet_3',['DashCamNet',['../md_jetson-inference_2docs_2detectnet-tao.html#autotoc_md214',1,'']]],
  ['data_4',['Data',['../md_jetson-inference_2docs_2pytorch-collect-detection.html#autotoc_md361',1,'Collecting Data'],['../md_jetson-inference_2docs_2pytorch-collect.html#autotoc_md366',1,'Collecting Data'],['../md_jetson-inference_2docs_2webrtc-recognizer.html#autotoc_md445',1,'Collecting Data'],['../md_jetson-inference_2docs_2pytorch-cat-dog.html#autotoc_md349',1,'Downloading the Data'],['../md_jetson-inference_2docs_2pytorch-plants.html#autotoc_md369',1,'Downloading the Data'],['../md_jetson-inference_2docs_2pytorch-ssd.html#autotoc_md378',1,'Downloading the Data'],['../md_jetson-inference_2docs_2pytorch-ssd.html#autotoc_md379',1,'Limiting the Amount of Data']]],
  ['data_20and_20job_20directories_5',['Setting up data and job directories',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md246',1,'']]],
  ['data_20and_20job_20directory_20for_20digits_6',['Setting up data and job directory for DIGITS',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md245',1,'']]],
  ['data_20formatting_20in_20digits_7',['Detection Data Formatting in DIGITS',['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md223',1,'']]],
  ['data_20in_20python_8',['Accessing Image Data in Python',['../md_jetson-inference_2docs_2aux-image.html#autotoc_md68',1,'']]],
  ['data_20optional_9',['Generating More Data (Optional)',['../md_jetson-inference_2docs_2pytorch-cat-dog.html#autotoc_md357',1,'']]],
  ['data_20parallel_20training_10',['Multi-processing Distributed Data Parallel Training',['../dir_74946e755fa1b443ff6e15cb05419b3e.html#autotoc_md460',1,'']]],
  ['data_20volumes_11',['Mounted Data Volumes',['../md_jetson-inference_2docs_2aux-docker.html#autotoc_md53',1,'']]],
  ['dataset_12',['Dataset',['../md_jetson-inference_2docs_2segnet-dataset.html#autotoc_md416',1,'Downloading Aerial Drone Dataset'],['../md_jetson-inference_2docs_2imagenet-training.html#autotoc_md322',1,'Downloading Image Recognition Dataset'],['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md224',1,'Downloading the Detection Dataset'],['../md_jetson-inference_2docs_2pytorch-cat-dog.html#autotoc_md348',1,'Re-training on the Cat/Dog Dataset'],['../md_jetson-inference_2docs_2pytorch-plants.html#autotoc_md368',1,'Re-training on the PlantCLEF Dataset']]],
  ['dataset_13',['segnet-dataset',['../md_jetson-inference_2docs_2segnet-dataset.html',1,'']]],
  ['dataset_20details_14',['2. Dataset Details',['../md_about.html#autotoc_md3',1,'']]],
  ['dataset_20into_20digits_15',['Dataset into DIGITS',['../md_jetson-inference_2docs_2imagenet-training.html#autotoc_md324',1,'Importing Classification Dataset into DIGITS'],['../md_jetson-inference_2docs_2segnet-dataset.html#autotoc_md417',1,'Importing the Aerial Dataset into DIGITS'],['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md225',1,'Importing the Detection Dataset into DIGITS']]],
  ['datasets_16',['Datasets',['../md_jetson-inference_2docs_2pytorch-collect.html#autotoc_md363',1,'Collecting your own Classification Datasets'],['../md_jetson-inference_2docs_2pytorch-collect-detection.html#autotoc_md358',1,'Collecting your own Detection Datasets'],['../md_jetson-inference_2docs_2pytorch-transfer-learning.html#autotoc_md390',1,'Training Datasets']]],
  ['days_20to_20a_20demo_20digits_17',['Two Days to a Demo (DIGITS)',['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md489',1,'']]],
  ['declaring_20main_20and_20parsing_20the_20command_20line_18',['Declaring main and Parsing the Command Line',['../md_jetson-inference_2docs_2imagenet-example-2.html#autotoc_md280',1,'Declaring main() and Parsing the Command Line'],['../md_jetson-inference_2docs_2imagenet-example.html#autotoc_md305',1,'Declaring main() and Parsing the Command Line']]],
  ['deep_20learning_19',['Deep Learning',['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md467',1,'Deploying Deep Learning'],['../md_jetson-inference_2docs_2deep-learning.html#autotoc_md159',1,'What&apos;s Deep Learning?']]],
  ['deep_20learning_20',['deep-learning',['../md_jetson-inference_2docs_2deep-learning.html',1,'']]],
  ['deepscene_21',['DeepScene',['../md_jetson-inference_2docs_2segnet-console-2.html#autotoc_md402',1,'']]],
  ['default_20behavior_22',['Default behavior',['../classnlohmann_1_1basic__json.html#autotoc_md28',1,'Default behavior'],['../classnlohmann_1_1basic__json.html#autotoc_md32',1,'Default behavior'],['../classnlohmann_1_1basic__json.html#autotoc_md36',1,'Default behavior'],['../classnlohmann_1_1basic__json.html#autotoc_md505',1,'Default behavior'],['../classnlohmann_1_1basic__json.html#autotoc_md509',1,'Default behavior'],['../classnlohmann_1_1basic__json.html#autotoc_md513',1,'Default behavior']]],
  ['default_20type_23',['Default type',['../classnlohmann_1_1basic__json.html#autotoc_md14',1,'Default type'],['../classnlohmann_1_1basic__json.html#autotoc_md18',1,'Default type'],['../classnlohmann_1_1basic__json.html#autotoc_md21',1,'Default type'],['../classnlohmann_1_1basic__json.html#autotoc_md25',1,'Default type'],['../classnlohmann_1_1basic__json.html#autotoc_md27',1,'Default type'],['../classnlohmann_1_1basic__json.html#autotoc_md31',1,'Default type'],['../classnlohmann_1_1basic__json.html#autotoc_md35',1,'Default type'],['../classnlohmann_1_1basic__json.html#autotoc_md39',1,'Default type'],['../classnlohmann_1_1basic__json.html#autotoc_md491',1,'Default type'],['../classnlohmann_1_1basic__json.html#autotoc_md495',1,'Default type'],['../classnlohmann_1_1basic__json.html#autotoc_md498',1,'Default type'],['../classnlohmann_1_1basic__json.html#autotoc_md502',1,'Default type'],['../classnlohmann_1_1basic__json.html#autotoc_md504',1,'Default type'],['../classnlohmann_1_1basic__json.html#autotoc_md508',1,'Default type'],['../classnlohmann_1_1basic__json.html#autotoc_md512',1,'Default type'],['../classnlohmann_1_1basic__json.html#autotoc_md516',1,'Default type']]],
  ['demo_24',['Demo',['../md_jetson-inference_2docs_2detectnet-camera-2.html#autotoc_md172',1,'Running the Live Camera Detection Demo'],['../md_jetson-inference_2docs_2detectnet-camera.html#autotoc_md177',1,'Running the Live Camera Detection Demo'],['../md_jetson-inference_2docs_2imagenet-camera-2.html#autotoc_md251',1,'Running the Live Camera Recognition Demo'],['../md_jetson-inference_2docs_2imagenet-camera.html#autotoc_md255',1,'Running the Live Camera Recognition Demo'],['../md_jetson-inference_2docs_2segnet-camera-2.html#autotoc_md391',1,'Running the Live Camera Segmentation Demo']]],
  ['demo_20digits_25',['Two Days to a Demo (DIGITS)',['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md489',1,'']]],
  ['dependencies_26',['1. Installing Dependencies',['../md_jetson-inference_2docs_2building-nvcaffe.html#autotoc_md124',1,'']]],
  ['deploying_20deep_20learning_27',['Deploying Deep Learning',['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md467',1,'']]],
  ['deprecated_20list_28',['Deprecated List',['../deprecated.html',1,'']]],
  ['depth_20field_29',['Getting the Raw Depth Field',['../md_jetson-inference_2docs_2depthnet.html#autotoc_md168',1,'']]],
  ['depth_20from_20video_30',['Mono Depth from Video',['../md_jetson-inference_2docs_2depthnet.html#autotoc_md167',1,'']]],
  ['depth_20on_20images_31',['Mono Depth on Images',['../md_jetson-inference_2docs_2depthnet.html#autotoc_md166',1,'']]],
  ['depth_20with_20depthnet_32',['Monocular Depth with DepthNet',['../md_jetson-inference_2docs_2depthnet.html#autotoc_md165',1,'']]],
  ['depthnet_33',['Monocular Depth with DepthNet',['../md_jetson-inference_2docs_2depthnet.html#autotoc_md165',1,'']]],
  ['depthnet_34',['depthnet',['../md_jetson-inference_2docs_2depthnet.html',1,'']]],
  ['desktop_20gui_35',['Disabling the Desktop GUI',['../md_jetson-inference_2docs_2pytorch-transfer-learning.html#autotoc_md389',1,'']]],
  ['destination_36',['Secondary Destination',['../md_jetson-inference_2docs_2aux-streaming.html#autotoc_md113',1,'']]],
  ['details_37',['2. Dataset Details',['../md_about.html#autotoc_md3',1,'']]],
  ['detecting_20objects_38',['Detecting Objects',['../md_jetson-inference_2docs_2detectnet-example-2.html#autotoc_md205',1,'']]],
  ['detecting_20objects_20from_20images_39',['Detecting Objects from Images',['../md_jetson-inference_2docs_2detectnet-console-2.html#autotoc_md183',1,'']]],
  ['detecting_20objects_20from_20the_20command_20line_40',['Detecting Objects from the Command Line',['../md_jetson-inference_2docs_2detectnet-console.html#autotoc_md190',1,'']]],
  ['detection_41',['Object Detection',['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md483',1,'']]],
  ['detection_42',['detection',['../md_jetson-inference_2docs_2pytorch-collect-detection.html',1,'pytorch-collect-detection'],['../dir_31e2642bab038cbfa041cb8a9a657ed5.html#autotoc_md464',1,'pytorch-detection']]],
  ['detection_20data_20formatting_20in_20digits_43',['Detection Data Formatting in DIGITS',['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md223',1,'']]],
  ['detection_20dataset_44',['Downloading the Detection Dataset',['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md224',1,'']]],
  ['detection_20dataset_20into_20digits_45',['Importing the Detection Dataset into DIGITS',['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md225',1,'']]],
  ['detection_20datasets_46',['Collecting your own Detection Datasets',['../md_jetson-inference_2docs_2pytorch-collect-detection.html#autotoc_md358',1,'']]],
  ['detection_20demo_47',['Detection Demo',['../md_jetson-inference_2docs_2detectnet-camera-2.html#autotoc_md172',1,'Running the Live Camera Detection Demo'],['../md_jetson-inference_2docs_2detectnet-camera.html#autotoc_md177',1,'Running the Live Camera Detection Demo']]],
  ['detection_20in_20pytorch_48',['SSD-based Object Detection in PyTorch',['../dir_b9fe602b15fcaa889e04a122946a3c8a.html#autotoc_md465',1,'']]],
  ['detection_20loop_20detector_20py_49',['Detection Loop (&lt;span class=&quot;tt&quot;&gt;detector.py&lt;/span&gt;)',['../md_about.html#autotoc_md10',1,'']]],
  ['detection_20model_50',['Loading the Detection Model',['../md_jetson-inference_2docs_2detectnet-example-2.html#autotoc_md201',1,'']]],
  ['detection_20model_20to_20jetson_51',['Downloading the Detection Model to Jetson',['../md_jetson-inference_2docs_2detectnet-snapshot.html#autotoc_md209',1,'']]],
  ['detection_20models_52',['Detection Models',['../md_jetson-inference_2docs_2detectnet-tao.html#autotoc_md216',1,'Importing Your Own TAO Detection Models'],['../md_jetson-inference_2docs_2detectnet-console.html#autotoc_md196',1,'Multi-class Object Detection Models'],['../md_jetson-inference_2docs_2detectnet-console-2.html#autotoc_md187',1,'Running Different Detection Models'],['../md_jetson-inference_2docs_2detectnet-console.html#autotoc_md195',1,'Running Different Detection Models'],['../md_jetson-inference_2docs_2detectnet-tao.html#autotoc_md212',1,'Using TAO Detection Models']]],
  ['detection_20models_20available_53',['Detection Models Available',['../md_jetson-inference_2docs_2detectnet-console-2.html#autotoc_md186',1,'Pre-trained Detection Models Available'],['../md_jetson-inference_2docs_2detectnet-console.html#autotoc_md194',1,'Pre-trained Detection Models Available']]],
  ['detection_20program_54',['Coding Your Own Object Detection Program',['../md_jetson-inference_2docs_2detectnet-example-2.html#autotoc_md198',1,'']]],
  ['detection_20yolov8_55',['A. Object Detection (YOLOv8)',['../md_about.html#autotoc_md6',1,'']]],
  ['detectnet_56',['DetectNet',['../md_jetson-inference_2docs_2detectnet-console-2.html#autotoc_md182',1,'Locating Objects with DetectNet'],['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md222',1,'Locating Objects with DetectNet']]],
  ['detectnet_20batch_20size_57',['Selecting DetectNet Batch Size',['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md227',1,'']]],
  ['detectnet_20camera_58',['detectnet-camera',['../md_jetson-inference_2docs_2detectnet-camera.html',1,'']]],
  ['detectnet_20camera_202_59',['detectnet-camera-2',['../md_jetson-inference_2docs_2detectnet-camera-2.html',1,'']]],
  ['detectnet_20console_60',['detectnet-console',['../md_jetson-inference_2docs_2detectnet-console.html',1,'']]],
  ['detectnet_20console_202_61',['detectnet-console-2',['../md_jetson-inference_2docs_2detectnet-console-2.html',1,'']]],
  ['detectnet_20example_202_62',['detectnet-example-2',['../md_jetson-inference_2docs_2detectnet-example-2.html',1,'']]],
  ['detectnet_20model_20inference_20in_20digits_63',['Testing DetectNet Model Inference in DIGITS',['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md230',1,'']]],
  ['detectnet_20model_20with_20digits_64',['Creating DetectNet Model with DIGITS',['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md226',1,'']]],
  ['detectnet_20patches_20for_20tensorrt_65',['DetectNet Patches for TensorRT',['../md_jetson-inference_2docs_2detectnet-snapshot.html#autotoc_md210',1,'']]],
  ['detectnet_20prototxt_66',['Specifying the DetectNet Prototxt',['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md228',1,'']]],
  ['detectnet_20snapshot_67',['detectnet-snapshot',['../md_jetson-inference_2docs_2detectnet-snapshot.html',1,'']]],
  ['detectnet_20tao_68',['detectnet-tao',['../md_jetson-inference_2docs_2detectnet-tao.html',1,'']]],
  ['detectnet_20tracking_69',['detectnet-tracking',['../md_jetson-inference_2docs_2detectnet-tracking.html',1,'']]],
  ['detectnet_20training_70',['detectnet-training',['../md_jetson-inference_2docs_2detectnet-training.html',1,'']]],
  ['detector_20py_71',['Detection Loop (&lt;span class=&quot;tt&quot;&gt;detector.py&lt;/span&gt;)',['../md_about.html#autotoc_md10',1,'']]],
  ['development_20packages_72',['Development Packages',['../md_jetson-inference_2docs_2building-repo-2.html#autotoc_md139',1,'Python Development Packages'],['../md_jetson-inference_2docs_2building-repo.html#autotoc_md150',1,'Python Development Packages']]],
  ['different_20classification_20models_73',['Different Classification Models',['../md_jetson-inference_2docs_2imagenet-console-2.html#autotoc_md262',1,'Using Different Classification Models'],['../md_jetson-inference_2docs_2imagenet-console.html#autotoc_md272',1,'Using Different Classification Models']]],
  ['different_20detection_20models_74',['Different Detection Models',['../md_jetson-inference_2docs_2detectnet-console-2.html#autotoc_md187',1,'Running Different Detection Models'],['../md_jetson-inference_2docs_2detectnet-console.html#autotoc_md195',1,'Running Different Detection Models']]],
  ['digging_20into_20the_20code_75',['Digging Into the Code',['../md_jetson-inference_2docs_2building-repo-2.html#autotoc_md143',1,'Digging Into the Code'],['../md_jetson-inference_2docs_2building-repo.html#autotoc_md155',1,'Digging Into the Code']]],
  ['digits_76',['DIGITS',['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md226',1,'Creating DetectNet Model with DIGITS'],['../md_jetson-inference_2docs_2imagenet-training.html#autotoc_md325',1,'Creating Image Classification Model with DIGITS'],['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md223',1,'Detection Data Formatting in DIGITS'],['../md_jetson-inference_2docs_2deep-learning.html#autotoc_md162',1,'DIGITS'],['../md_jetson-inference_2docs_2imagenet-training.html#autotoc_md324',1,'Importing Classification Dataset into DIGITS'],['../md_jetson-inference_2docs_2segnet-dataset.html#autotoc_md417',1,'Importing the Aerial Dataset into DIGITS'],['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md225',1,'Importing the Detection Dataset into DIGITS'],['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md245',1,'Setting up data and job directory for DIGITS'],['../md_jetson-inference_2docs_2imagenet-training.html#autotoc_md326',1,'Testing Classification Model in DIGITS'],['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md230',1,'Testing DetectNet Model Inference in DIGITS'],['../md_jetson-inference_2docs_2segnet-training.html#autotoc_md424',1,'Testing Inference Model in DIGITS'],['../md_jetson-inference_2docs_2segnet-training.html#autotoc_md423',1,'Training FCN-Alexnet with DIGITS'],['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md489',1,'Two Days to a Demo (DIGITS)']]],
  ['digits_20container_77',['Starting DIGITS container',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md247',1,'']]],
  ['digits_20native_78',['digits-native',['../md_jetson-inference_2docs_2digits-native.html',1,'']]],
  ['digits_20on_20the_20host_79',['DIGITS on the Host',['../md_jetson-inference_2docs_2digits-native.html#autotoc_md236',1,'Installing DIGITS on the Host'],['../md_jetson-inference_2docs_2digits-native.html#autotoc_md232',1,'Natively setting up DIGITS on the Host']]],
  ['digits_20server_80',['Starting the DIGITS Server',['../md_jetson-inference_2docs_2digits-native.html#autotoc_md237',1,'']]],
  ['digits_20setup_81',['digits-setup',['../md_jetson-inference_2docs_2digits-setup.html',1,'']]],
  ['digits_20system_20setup_82',['DIGITS System Setup',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md239',1,'']]],
  ['digits_20workflow_83',['DIGITS Workflow',['../md_jetson-inference_2docs_2digits-workflow.html#autotoc_md249',1,'']]],
  ['digits_20workflow_84',['digits-workflow',['../md_jetson-inference_2docs_2digits-workflow.html',1,'']]],
  ['directories_85',['Setting up data and job directories',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md246',1,'']]],
  ['directory_20for_20digits_86',['Setting up data and job directory for DIGITS',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md245',1,'']]],
  ['directory_20or_20sequence_20of_20images_87',['Directory or Sequence of Images',['../md_jetson-inference_2docs_2detectnet-console-2.html#autotoc_md184',1,'Processing a Directory or Sequence of Images'],['../md_jetson-inference_2docs_2segnet-console-2.html#autotoc_md411',1,'Processing a Directory or Sequence of Images']]],
  ['disabling_20the_20desktop_20gui_88',['Disabling the Desktop GUI',['../md_jetson-inference_2docs_2pytorch-transfer-learning.html#autotoc_md389',1,'']]],
  ['disk_89',['Disk',['../md_jetson-inference_2docs_2imagenet-example-2.html#autotoc_md281',1,'Loading the Image from Disk'],['../md_jetson-inference_2docs_2imagenet-example-python-2.html#autotoc_md295',1,'Loading the Image from Disk'],['../md_jetson-inference_2docs_2imagenet-example.html#autotoc_md306',1,'Loading the Image from Disk']]],
  ['display_20loop_90',['Display Loop',['../md_jetson-inference_2docs_2detectnet-example-2.html#autotoc_md203',1,'']]],
  ['distributed_20data_20parallel_20training_91',['Multi-processing Distributed Data Parallel Training',['../dir_74946e755fa1b443ff6e15cb05419b3e.html#autotoc_md460',1,'']]],
  ['dnn_20models_92',['DNN Models',['../md_jetson-inference_2docs_2webrtc-dash.html#autotoc_md428',1,'Loading DNN Models'],['../md_jetson-inference_2docs_2webrtc-flask.html#autotoc_md437',1,'Loading DNN Models'],['../md_jetson-inference_2docs_2webrtc-html.html#autotoc_md441',1,'Loading DNN Models']]],
  ['docker_93',['Installing Docker',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md243',1,'']]],
  ['docker_94',['aux-docker',['../md_jetson-inference_2docs_2aux-docker.html',1,'']]],
  ['docker_20container_95',['Running the Docker Container',['../md_jetson-inference_2docs_2aux-docker.html#autotoc_md49',1,'']]],
  ['documentation_96',['Documentation',['../dir_24f5d2e6f66986322dddc02d8dd8aa7a.html#autotoc_md520',1,'']]],
  ['dog_97',['pytorch-cat-dog',['../md_jetson-inference_2docs_2pytorch-cat-dog.html',1,'']]],
  ['dog_20dataset_98',['Re-training on the Cat/Dog Dataset',['../md_jetson-inference_2docs_2pytorch-cat-dog.html#autotoc_md348',1,'']]],
  ['down_99',['Down',['../md_jetson-inference_2docs_2imagenet-example-2.html#autotoc_md285',1,'Shutting Down'],['../md_jetson-inference_2docs_2imagenet-example.html#autotoc_md310',1,'Shutting Down']]],
  ['downloading_20aerial_20drone_20dataset_100',['Downloading Aerial Drone Dataset',['../md_jetson-inference_2docs_2segnet-dataset.html#autotoc_md416',1,'']]],
  ['downloading_20image_20recognition_20dataset_101',['Downloading Image Recognition Dataset',['../md_jetson-inference_2docs_2imagenet-training.html#autotoc_md322',1,'']]],
  ['downloading_20model_20snapshots_20to_20jetson_102',['Downloading Model Snapshots to Jetson',['../md_jetson-inference_2docs_2imagenet-snapshot.html#autotoc_md315',1,'']]],
  ['downloading_20models_103',['Downloading Models',['../md_jetson-inference_2docs_2building-repo.html#autotoc_md152',1,'']]],
  ['downloading_20other_20classification_20models_104',['Downloading Other Classification Models',['../md_jetson-inference_2docs_2imagenet-console-2.html#autotoc_md261',1,'Downloading Other Classification Models'],['../md_jetson-inference_2docs_2imagenet-console.html#autotoc_md271',1,'Downloading Other Classification Models']]],
  ['downloading_20the_20data_105',['Downloading the Data',['../md_jetson-inference_2docs_2pytorch-cat-dog.html#autotoc_md349',1,'Downloading the Data'],['../md_jetson-inference_2docs_2pytorch-plants.html#autotoc_md369',1,'Downloading the Data'],['../md_jetson-inference_2docs_2pytorch-ssd.html#autotoc_md378',1,'Downloading the Data']]],
  ['downloading_20the_20detection_20dataset_106',['Downloading the Detection Dataset',['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md224',1,'']]],
  ['downloading_20the_20detection_20model_20to_20jetson_107',['Downloading the Detection Model to Jetson',['../md_jetson-inference_2docs_2detectnet-snapshot.html#autotoc_md209',1,'']]],
  ['drawing_20shapes_108',['Drawing Shapes',['../md_jetson-inference_2docs_2aux-image.html#autotoc_md89',1,'']]],
  ['driver_109',['Installing the NVIDIA driver',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md242',1,'']]],
  ['driver_20on_20the_20host_110',['Installing NVIDIA Driver on the Host',['../md_jetson-inference_2docs_2digits-native.html#autotoc_md233',1,'']]],
  ['drone_20dataset_111',['Downloading Aerial Drone Dataset',['../md_jetson-inference_2docs_2segnet-dataset.html#autotoc_md416',1,'']]],
  ['duplex_112',['Full Duplex',['../md_jetson-inference_2docs_2webrtc-server.html#autotoc_md454',1,'']]]
];
