var searchData=
[
  ['s_20deep_20learning_0',['What&apos;s Deep Learning?',['../md_jetson-inference_2docs_2deep-learning.html#autotoc_md159',1,'']]],
  ['samples_1',['samples',['../md_jetson-inference_2docs_2other-examples.html#autotoc_md340',1,'3. Build samples'],['../md_jetson-inference_2docs_2other-examples.html#autotoc_md341',1,'4. Running samples'],['../md_jetson-inference_2docs_2other-examples.html#autotoc_md336',1,'GPU Inference Engine (GIE) samples']]],
  ['samples_20c_2',['Inference Samples (C++)',['../dir_c4e9c01cc410ef4363235b7dfdd81ea6.html#autotoc_md455',1,'']]],
  ['samples_20python_3',['Inference Samples (Python)',['../dir_6d220aa666a3d416aa848fde12ec8b4e.html#autotoc_md456',1,'']]],
  ['satisfies_20the_20following_20concept_20requirements_3a_4',['class satisfies the following concept requirements:',['../requirements.html#The',1,'']]],
  ['secondary_20destination_5',['Secondary Destination',['../md_jetson-inference_2docs_2aux-streaming.html#autotoc_md113',1,'']]],
  ['segmentation_6',['Semantic Segmentation',['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md484',1,'']]],
  ['segmentation_7',['pytorch-segmentation',['../dir_562fb6c60cc405775d03623eda7d1a7a.html#autotoc_md466',1,'']]],
  ['segmentation_20demo_8',['Running the Live Camera Segmentation Demo',['../md_jetson-inference_2docs_2segnet-camera-2.html#autotoc_md391',1,'']]],
  ['segmentation_20models_20available_9',['Pre-Trained Segmentation Models Available',['../md_jetson-inference_2docs_2segnet-console-2.html#autotoc_md397',1,'']]],
  ['segmentation_20models_20on_20jetson_10',['Running Segmentation Models on Jetson',['../md_jetson-inference_2docs_2segnet-console.html#autotoc_md413',1,'']]],
  ['segmentation_20with_20segnet_11',['Segmentation with SegNet',['../md_jetson-inference_2docs_2segnet-console-2.html#autotoc_md396',1,'Semantic Segmentation with SegNet'],['../md_jetson-inference_2docs_2segnet-dataset.html#autotoc_md415',1,'Semantic Segmentation with SegNet']]],
  ['segmenting_20images_20from_20the_20command_20line_12',['Segmenting Images from the Command Line',['../md_jetson-inference_2docs_2segnet-console-2.html#autotoc_md398',1,'']]],
  ['segnet_13',['SegNet',['../md_jetson-inference_2docs_2segnet-console-2.html#autotoc_md396',1,'Semantic Segmentation with SegNet'],['../md_jetson-inference_2docs_2segnet-dataset.html#autotoc_md415',1,'Semantic Segmentation with SegNet']]],
  ['segnet_20camera_202_14',['segnet-camera-2',['../md_jetson-inference_2docs_2segnet-camera-2.html',1,'']]],
  ['segnet_20console_15',['segnet-console',['../md_jetson-inference_2docs_2segnet-console.html',1,'']]],
  ['segnet_20console_202_16',['segnet-console-2',['../md_jetson-inference_2docs_2segnet-console-2.html',1,'']]],
  ['segnet_20dataset_17',['segnet-dataset',['../md_jetson-inference_2docs_2segnet-dataset.html',1,'']]],
  ['segnet_20patches_18',['segnet-patches',['../md_jetson-inference_2docs_2segnet-patches.html',1,'']]],
  ['segnet_20pretrained_19',['segnet-pretrained',['../md_jetson-inference_2docs_2segnet-pretrained.html',1,'']]],
  ['segnet_20training_20',['segnet-training',['../md_jetson-inference_2docs_2segnet-training.html',1,'']]],
  ['selecting_20detectnet_20batch_20size_21',['Selecting DetectNet Batch Size',['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md227',1,'']]],
  ['semantic_20segmentation_22',['Semantic Segmentation',['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md484',1,'']]],
  ['semantic_20segmentation_20with_20segnet_23',['Semantic Segmentation with SegNet',['../md_jetson-inference_2docs_2segnet-console-2.html#autotoc_md396',1,'Semantic Segmentation with SegNet'],['../md_jetson-inference_2docs_2segnet-dataset.html#autotoc_md415',1,'Semantic Segmentation with SegNet']]],
  ['sending_20webrtc_20streams_24',['Sending WebRTC Streams',['../md_jetson-inference_2docs_2webrtc-server.html#autotoc_md450',1,'']]],
  ['sequence_20of_20images_25',['Sequence of Images',['../md_jetson-inference_2docs_2detectnet-console-2.html#autotoc_md184',1,'Processing a Directory or Sequence of Images'],['../md_jetson-inference_2docs_2segnet-console-2.html#autotoc_md411',1,'Processing a Directory or Sequence of Images']]],
  ['sequences_26',['Sequences',['../md_jetson-inference_2docs_2aux-streaming.html#autotoc_md115',1,'']]],
  ['server_27',['Server',['../md_jetson-inference_2docs_2digits-native.html#autotoc_md237',1,'Starting the DIGITS Server'],['../md_jetson-inference_2docs_2webrtc-server.html#autotoc_md448',1,'WebRTC Server']]],
  ['server_28',['webrtc-server',['../md_jetson-inference_2docs_2webrtc-server.html',1,'']]],
  ['set_20environment_20paths_29',['5. Set environment paths',['../md_jetson-inference_2docs_2building-nvcaffe.html#autotoc_md133',1,'']]],
  ['setting_20up_20data_20and_20job_20directories_30',['Setting up data and job directories',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md246',1,'']]],
  ['setting_20up_20data_20and_20job_20directory_20for_20digits_31',['Setting up data and job directory for DIGITS',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md245',1,'']]],
  ['setting_20up_20digits_20on_20the_20host_32',['Natively setting up DIGITS on the Host',['../md_jetson-inference_2docs_2digits-native.html#autotoc_md232',1,'']]],
  ['setting_20up_20host_20training_20pc_20with_20ngc_20container_33',['Setting up host training PC with NGC container',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md241',1,'']]],
  ['setting_20up_20jetson_20with_20jetpack_34',['Setting up Jetson with JetPack',['../md_jetson-inference_2docs_2jetpack-setup-2.html#autotoc_md328',1,'Setting up Jetson with JetPack'],['../md_jetson-inference_2docs_2jetpack-setup.html#autotoc_md333',1,'Setting up Jetson with JetPack']]],
  ['setting_20up_20the_20project_35',['Setting up the Project',['../md_jetson-inference_2docs_2imagenet-example-2.html#autotoc_md277',1,'Setting up the Project'],['../md_jetson-inference_2docs_2imagenet-example-python-2.html#autotoc_md291',1,'Setting up the Project'],['../md_jetson-inference_2docs_2imagenet-example.html#autotoc_md302',1,'Setting up the Project']]],
  ['setup_36',['Setup',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md239',1,'DIGITS System Setup'],['../md_jetson-inference_2docs_2pytorch-ssd.html#autotoc_md377',1,'Setup'],['../md__r_e_a_d_m_e.html#autotoc_md524',1,'Setup'],['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md470',1,'System Setup']]],
  ['setup_37',['setup',['../md_jetson-inference_2docs_2digits-setup.html',1,'digits-setup'],['../md_jetson-inference_2docs_2jetpack-setup.html',1,'jetpack-setup']]],
  ['setup_202_38',['jetpack-setup-2',['../md_jetson-inference_2docs_2jetpack-setup-2.html',1,'']]],
  ['setup_20build_20options_39',['3. Setup build options',['../md_jetson-inference_2docs_2building-nvcaffe.html#autotoc_md126',1,'']]],
  ['setup_20header_20linker_20paths_40',['Setup header/linker paths',['../md_jetson-inference_2docs_2building-nvcaffe.html#autotoc_md130',1,'']]],
  ['shapes_41',['Drawing Shapes',['../md_jetson-inference_2docs_2aux-image.html#autotoc_md89',1,'']]],
  ['sharing_20the_20memory_20pointer_42',['Sharing the Memory Pointer',['../md_jetson-inference_2docs_2aux-image.html#autotoc_md73',1,'']]],
  ['shutting_20down_43',['Shutting Down',['../md_jetson-inference_2docs_2imagenet-example-2.html#autotoc_md285',1,'Shutting Down'],['../md_jetson-inference_2docs_2imagenet-example.html#autotoc_md310',1,'Shutting Down']]],
  ['sign_20up_44',['NGC Sign-up',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md244',1,'']]],
  ['single_20node_20multiple_20gpus_3a_45',['Single node, multiple GPUs:',['../dir_74946e755fa1b443ff6e15cb05419b3e.html#autotoc_md461',1,'']]],
  ['size_46',['Selecting DetectNet Batch Size',['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md227',1,'']]],
  ['sm_5f53_3a_47',['Enable compute_53/sm_53:',['../md_jetson-inference_2docs_2building-nvcaffe.html#autotoc_md129',1,'']]],
  ['snapshot_48',['snapshot',['../md_jetson-inference_2docs_2detectnet-snapshot.html',1,'detectnet-snapshot'],['../md_jetson-inference_2docs_2imagenet-snapshot.html',1,'imagenet-snapshot']]],
  ['snapshots_20to_20jetson_49',['Downloading Model Snapshots to Jetson',['../md_jetson-inference_2docs_2imagenet-snapshot.html#autotoc_md315',1,'']]],
  ['source_50',['Source',['../dir_24f5d2e6f66986322dddc02d8dd8aa7a.html#autotoc_md521',1,'Building from Source'],['../md_jetson-inference_2docs_2building-repo-2.html#autotoc_md136',1,'Building the Project from Source'],['../md_jetson-inference_2docs_2building-repo.html#autotoc_md147',1,'Building the Project from Source']]],
  ['source_20code_51',['Source Code',['../md_jetson-inference_2docs_2aux-streaming.html#autotoc_md116',1,'Source Code'],['../md_jetson-inference_2docs_2detectnet-console-2.html#autotoc_md188',1,'Source Code'],['../md_jetson-inference_2docs_2detectnet-example-2.html#autotoc_md199',1,'Source Code'],['../md_jetson-inference_2docs_2imagenet-example-2.html#autotoc_md278',1,'Source Code'],['../md_jetson-inference_2docs_2imagenet-example-python-2.html#autotoc_md292',1,'Source Code'],['../md_jetson-inference_2docs_2imagenet-example.html#autotoc_md303',1,'Source Code']]],
  ['source_20listing_52',['Source Listing',['../md_jetson-inference_2docs_2detectnet-example-2.html#autotoc_md207',1,'']]],
  ['specifying_20the_20detectnet_20prototxt_53',['Specifying the DetectNet Prototxt',['../md_jetson-inference_2docs_2detectnet-training.html#autotoc_md228',1,'']]],
  ['ssd_54',['pytorch-ssd',['../md_jetson-inference_2docs_2pytorch-ssd.html',1,'']]],
  ['ssd_20based_20object_20detection_20in_20pytorch_55',['SSD-based Object Detection in PyTorch',['../dir_b9fe602b15fcaa889e04a122946a3c8a.html#autotoc_md465',1,'']]],
  ['ssd_20mobilenet_56',['Re-training SSD-Mobilenet',['../md_jetson-inference_2docs_2pytorch-ssd.html#autotoc_md376',1,'']]],
  ['ssd_20mobilenet_20model_57',['Training the SSD-Mobilenet Model',['../md_jetson-inference_2docs_2pytorch-ssd.html#autotoc_md381',1,'']]],
  ['ssl_58',['Enabling HTTPS / SSL',['../md_jetson-inference_2docs_2webrtc-server.html#autotoc_md449',1,'']]],
  ['started_59',['Getting Started',['../md_jetson-inference_2docs_2aux-docker.html#autotoc_md56',1,'']]],
  ['starting_20digits_20container_60',['Starting DIGITS container',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md247',1,'']]],
  ['starting_20the_20digits_20server_61',['Starting the DIGITS Server',['../md_jetson-inference_2docs_2digits-native.html#autotoc_md237',1,'']]],
  ['state_62',['Tracking State',['../md_jetson-inference_2docs_2detectnet-tracking.html#autotoc_md221',1,'']]],
  ['storage_63',['Storage',['../classnlohmann_1_1basic__json.html#autotoc_md17',1,'Storage'],['../classnlohmann_1_1basic__json.html#autotoc_md20',1,'Storage'],['../classnlohmann_1_1basic__json.html#autotoc_md24',1,'Storage'],['../classnlohmann_1_1basic__json.html#autotoc_md26',1,'Storage'],['../classnlohmann_1_1basic__json.html#autotoc_md30',1,'Storage'],['../classnlohmann_1_1basic__json.html#autotoc_md34',1,'Storage'],['../classnlohmann_1_1basic__json.html#autotoc_md38',1,'Storage'],['../classnlohmann_1_1basic__json.html#autotoc_md40',1,'Storage'],['../classnlohmann_1_1basic__json.html#autotoc_md494',1,'Storage'],['../classnlohmann_1_1basic__json.html#autotoc_md497',1,'Storage'],['../classnlohmann_1_1basic__json.html#autotoc_md501',1,'Storage'],['../classnlohmann_1_1basic__json.html#autotoc_md503',1,'Storage'],['../classnlohmann_1_1basic__json.html#autotoc_md507',1,'Storage'],['../classnlohmann_1_1basic__json.html#autotoc_md511',1,'Storage'],['../classnlohmann_1_1basic__json.html#autotoc_md515',1,'Storage'],['../classnlohmann_1_1basic__json.html#autotoc_md517',1,'Storage']]],
  ['stream_64',['Opening the Camera Stream',['../md_jetson-inference_2docs_2detectnet-example-2.html#autotoc_md202',1,'']]],
  ['streaming_65',['Live Streaming',['../md_jetson-inference_2docs_2backgroundnet.html#autotoc_md121',1,'']]],
  ['streaming_66',['aux-streaming',['../md_jetson-inference_2docs_2aux-streaming.html',1,'']]],
  ['streaming_20and_20multimedia_67',['Camera Streaming and Multimedia',['../md_jetson-inference_2docs_2aux-streaming.html#autotoc_md93',1,'']]],
  ['streams_68',['Streams',['../md_jetson-inference_2docs_2webrtc-dash.html#autotoc_md430',1,'Creating Streams'],['../md_jetson-inference_2docs_2aux-streaming.html#autotoc_md94',1,'Input Streams'],['../md_jetson-inference_2docs_2aux-streaming.html#autotoc_md95',1,'Output Streams'],['../md_jetson-inference_2docs_2webrtc-server.html#autotoc_md452',1,'Receiving WebRTC Streams'],['../md_jetson-inference_2docs_2webrtc-server.html#autotoc_md450',1,'Sending WebRTC Streams']]],
  ['string_20comparison_69',['String comparison',['../classnlohmann_1_1basic__json.html#autotoc_md23',1,'String comparison'],['../classnlohmann_1_1basic__json.html#autotoc_md500',1,'String comparison']]],
  ['structure_70',['Structure',['../md__r_e_a_d_m_e.html#autotoc_md523',1,'']]],
  ['subtypes_71',['subtypes',['../classnlohmann_1_1basic__json.html#autotoc_md41',1,'Notes on subtypes'],['../classnlohmann_1_1basic__json.html#autotoc_md518',1,'Notes on subtypes']]],
  ['sun_20classes_72',['SUN Classes',['../md_jetson-inference_2docs_2segnet-console-2.html#autotoc_md410',1,'']]],
  ['sun_20rgb_20d_73',['SUN RGB-D',['../md_jetson-inference_2docs_2segnet-console-2.html#autotoc_md409',1,'']]],
  ['support_74',['Support',['../md_jetson-inference_2docs_2aux-docker.html#autotoc_md51',1,'ROS Support'],['../md_jetson-inference_2docs_2aux-docker.html#autotoc_md52',1,'x86 Support']]],
  ['swap_75',['Mounting Swap',['../md_jetson-inference_2docs_2pytorch-transfer-learning.html#autotoc_md388',1,'']]],
  ['system_20requirements_76',['Recommended System Requirements',['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md487',1,'']]],
  ['system_20setup_77',['System Setup',['../md_jetson-inference_2docs_2digits-setup.html#autotoc_md239',1,'DIGITS System Setup'],['../dir_5fcaaf5af391369b2d07f8dcd23285dd.html#autotoc_md470',1,'System Setup']]]
];
